inst_Items = {
	{ item_instance = "huzvui_itar_conq", 						friendly_name = "Кираса поверх дублета"	 	},
	{ item_instance = "huzvui_itar_varant_l", 						friendly_name = "Одеяние варантца"	 	},
	{ item_instance = "huzvui_itar_varant_m", 						friendly_name = "Доспехи варантца"	 	},
	{ item_instance = "huzvui_itar_varant_h", 						friendly_name = "Тяжелые доспехи варантца"	 	},
	{ item_instance = "huzvui_itar_nord_l", 						friendly_name = "Легкие доспехи нордмарца"	 	},
	{ item_instance = "huzvui_itar_nord_m", 						friendly_name = "Доспехи воина-нордмарца"	 	},
	{ item_instance = "huzvui_itar_nord_h", 						friendly_name = "Тяжелые доспехи нордмарца"	 	},
	{ item_instance = "huzvui_itar_nord_lord", 						friendly_name = "Доспехи нордмарского вождя"	 	},
	{ item_instance = "huzvui_itar_king", 						friendly_name = "Доспехи короля"	 	},
	{ item_instance = "huzvui_itar_lord", 						friendly_name = "Одеяние дворянина"	 	},
	{ item_instance = "huzvui_itar_hedge_l", 						friendly_name = "Доспех межевого рыцаря"	 	},
	{ item_instance = "huzvui_itar_vlk_fur", 						friendly_name = "Дублет с меховой накидкой"	 	},
	{ item_instance = "huzvui_itar_geralt", 						friendly_name = "Одежда авантюриста"	 	},
	{ item_instance = "huzvui_itar_pestdoktor", 						friendly_name = "Одеяние чумного доктора"	 	},
	{ item_instance = "huzvui_itar_vlk_sh", 						friendly_name = "Плащ горожанина"	 	},
	{ item_instance = "huzvui_itar_vlk_h_01", 						friendly_name = "Роскошный Плащ горожанина"	 	},
	{ item_instance = "huzvui_itar_vlk_h_02", 						friendly_name = "Роскошный плащ горожанина"	 	},
	{ item_instance = "huzvui_itar_governor", 						friendly_name = "Роскошный дублет"	 	},
	{ item_instance = "huzvui_itar_leather_l", 						friendly_name = "Кожаная куртка"	 	},
	{ item_instance = "huzvui_itar_judge", 						friendly_name = "Мантия судьи"	 	},
	{ item_instance = "huzvui_itar_smith", 						friendly_name = "Одежда кузнеца"	 	},
	{ item_instance = "huzvui_itar_barkeeper", 						friendly_name = "Одежда трактирщика"	 	},
	{ item_instance = "huzvui_itar_vlk_l", 						friendly_name = "Коричневый дублет"	 	},
	{ item_instance = "huzvui_itar_vlk_m", 						friendly_name = "Розовый дублет"	 	},
	{ item_instance = "huzvui_itar_vlk_h", 						friendly_name = "Богатый дублет"	 	},
	{ item_instance = "huzvui_itar_vlkbabe_l", 						friendly_name = "Голубое платье горожанки"	 	},
	{ item_instance = "huzvui_itar_vlkbabe_m", 						friendly_name = "Белое платье горожанки"	 	},
	{ item_instance = "huzvui_itar_vlkbabe_h", 						friendly_name = "Черное платье горожанки"	 	},
	{ item_instance = "huzvui_itar_bau_l", 						friendly_name = "Крестьянская одежда"	 	},
	{ item_instance = "huzvui_itar_bau_m", 						friendly_name = "Жилет фермера"	 	},
	{ item_instance = "huzvui_itar_baubabe_l", 						friendly_name = "Крестьянское платье"	 	},
	{ item_instance = "huzvui_itar_prisoner", 						friendly_name = "Штаны рудокопа"	 	},
	{ item_instance = "huzvui_itar_nov_l", 						friendly_name = "Роба послушника Огня"	 	},
	{ item_instance = "huzvui_nov_armor_l", 						friendly_name = "Повязка послушника Братства"	 	},
	{ item_instance = "huzvui_nov_armor_m", 						friendly_name = "Роба послушника Братства"	 	},
	{ item_instance = "huzvui_itar_hobo_01", 						friendly_name = "Штаны бедняка"	 	},
	{ item_instance = "huzvui_itar_hobo_02", 						friendly_name = "Штаны бедняка"	 	},
	{ item_instance = "huzvui_itar_hobo_03", 						friendly_name = "Штаны бедняка"	 	},
	{ item_instance = "huzvui_itar_hobo_04", 						friendly_name = "Штаны бедняка"	 	},
	{ item_instance = "huzvui_itar_sailor_01", 						friendly_name = "Одежда моряка"	 	},
	{ item_instance = "huzvui_itar_sailor_02", 						friendly_name = "Одежда моряка"	 	},
	{ item_instance = "huzvui_itar_sailor_03", 						friendly_name = "Одежда моряка"	 	},
	{ item_instance = "huzvui_itar_sailor_04", 						friendly_name = "Одежда моряка"	 	},
	{ item_instance = "huzvui_itar_baul_01", 						friendly_name = "Рабочая одежда"	 	},
	{ item_instance = "huzvui_itar_baul_02", 						friendly_name = "Рабочая одежда"	 	},
	{ item_instance = "huzvui_itar_baul_03", 						friendly_name = "Рабочая одежда"	 	},
	{ item_instance = "huzvui_itar_baum_01", 						friendly_name = "Коричневый жилет крестьянина"	 	},
	{ item_instance = "huzvui_itar_baum_02", 						friendly_name = "Синий жилет крестьянина"	 	},
	{ item_instance = "huzvui_itar_baum_03", 						friendly_name = "Серый жилет крестьянина"	 	},
	{ item_instance = "huzvui_itar_vlk_01", 						friendly_name = "Потрепанная куртка"	 	},
	{ item_instance = "huzvui_itar_vlk_02", 						friendly_name = "Черный дублет"	 	},
	{ item_instance = "huzvui_itar_vlk_03", 						friendly_name = "Дорогой дублет"	 	},
	{ item_instance = "huzvui_itar_vlk_04", 						friendly_name = "Розовый стеганый дублет"	 	},
	{ item_instance = "huzvui_itar_vlk_05", 						friendly_name = "Куртка горожанина"	 	},
	{ item_instance = "huzvui_itar_vlk_06", 						friendly_name = "Коричневый дублет"	 	},
	{ item_instance = "huzvui_itar_vlk_07", 						friendly_name = "Стеганый сублет богача"	 	},
	{ item_instance = "huzvui_itar_vlk_08", 						friendly_name = "Коричневый дублет"	 	},
	{ item_instance = "huzvui_itar_vlk_09", 						friendly_name = "Серый дублет"	 	},
	{ item_instance = "huzvui_itar_vlk_10", 						friendly_name = "Черный стеганый дублет"	 	},
	{ item_instance = "huzvui_itar_vlk_11", 						friendly_name = "Красный дублет"	 	},
	{ item_instance = "huzvui_itar_trv_01", 						friendly_name = "Зеленый плащ"	 	},
	{ item_instance = "huzvui_itar_trv_02", 						friendly_name = "Синий плащ"	 	},
	{ item_instance = "huzvui_itar_trv_03", 						friendly_name = "Кожаный плащ"	 	},
	{ item_instance = "huzvui_itar_trv_04", 						friendly_name = "Черный плащ"	 	},
	{ item_instance = "huzvui_itar_rich_01", 						friendly_name = "Зеленый камзол"	 	},
	{ item_instance = "huzvui_itar_rich_02", 						friendly_name = "Синий камзол"	 	},
	{ item_instance = "huzvui_itar_rich_03", 						friendly_name = "Красный камзол"	 	},
	{ item_instance = "huzvui_itar_rich_04", 						friendly_name = "Черный камзол"	 	},
	{ item_instance = "huzvui_itar_richest_01", 						friendly_name = "Роскошный желтый камзол"	 	},
	{ item_instance = "huzvui_itar_richest_02", 						friendly_name = "Роскошный алый камзол"	 	},
	{ item_instance = "huzvui_itar_richest_03", 						friendly_name = "Роскошный синий камзол"	 	},
	{ item_instance = "huzvui_itar_richest_04", 						friendly_name = "Роскошный пурпурный камзол"	 	},
	{ item_instance = "huzvui_itar_babe_wedding", 						friendly_name = "Подвенечное платье"	 	},
	{ item_instance = "huzvui_itar_babe_bau", 						friendly_name = "Платье крестьянки"	 	},
	{ item_instance = "huzvui_itar_babe_poor", 						friendly_name = "Платье нищенки"	 	},
	{ item_instance = "huzvui_itar_babe_simple", 						friendly_name = "Домотканое платье"	 	},
	{ item_instance = "huzvui_itar_babe_rich_01", 						friendly_name = "Роскошное фиалковое платье"	 	},
	{ item_instance = "huzvui_itar_babe_rich_02", 						friendly_name = "Роскошное розовое платье"	 	},
	{ item_instance = "huzvui_itar_babe_rich_03", 						friendly_name = "Роскошное зеленое платье"	 	},
	{ item_instance = "huzvui_itar_babe_rich_04", 						friendly_name = "Роскошное оранжевое платье"	 	},
	{ item_instance = "huzvui_itar_mil_l", 						friendly_name = "легкие доспехи ополчения"	 	},
	{ item_instance = "huzvui_itar_bdt_m", 						friendly_name = "Легкие меховые доспехи"	 	},
	{ item_instance = "huzvui_itar_pir_l", 						friendly_name = "Одежда пирата"	 	},
	{ item_instance = "huzvui_stt_armor_m", 						friendly_name = "Одежда Призрака"	 	},
	{ item_instance = "huzvui_grd_armor_l", 						friendly_name = "Легкие доспехи стражника"	 	},
	{ item_instance = "huzvui_org_armor_l", 						friendly_name = "Легкие доспехи вора"	 	},
	{ item_instance = "huzvui_nov_armor_h", 						friendly_name = "Доспехи послушника Братства"	 	},
	{ item_instance = "huzvui_kdf_armor_l", 						friendly_name = "Роба мага Огня"	 	},
	{ item_instance = "huzvui_itar_hunter_old", 						friendly_name = "Старая кожаная куртка"	 	},
	{ item_instance = "huzvui_itar_woodcutter", 						friendly_name = "Куртка лесоруба"	 	},
	{ item_instance = "huzvui_itar_hunter_01", 						friendly_name = "Кожаная куртка"	 	},
	{ item_instance = "huzvui_itar_hunter_02", 						friendly_name = "Черная кожаная куртка"	 	},
	{ item_instance = "huzvui_itar_hunter_03", 						friendly_name = "Черная кожаная куртка"	 	},
	{ item_instance = "huzvui_itar_leather_m", 						friendly_name = "Легкий кожаный доспех"	 	},
	{ item_instance = "huzvui_itar_chain_l", 						friendly_name = "Легкая кольчуга"	 	},
	{ item_instance = "huzvui_itar_sth_l", 						friendly_name = "Одеяние южанина"	 	},
	{ item_instance = "huzvui_itar_aketon", 						friendly_name = "Двухцветный акетон"	 	},
	{ item_instance = "huzvui_itar_mil_aketon", 						friendly_name = "Акетон стражника"	 	},
	{ item_instance = "huzvui_itar_arx_run", 						friendly_name = "Одежда гонца Араксос"	 	},
	{ item_instance = "huzvui_itar_ivy_01", 						friendly_name = "Черный кожаный доспех"	 	},
	{ item_instance = "huzvui_itar_ivy_02", 						friendly_name = "Кожаный доспех"	 	},
	{ item_instance = "huzvui_itar_ivy_03", 						friendly_name = "Черно-красный кожаный доспех"	 	},
	{ item_instance = "huzvui_itar_row_l", 						friendly_name = "Доспехи Кольца Воды"	 	},
	{ item_instance = "huzvui_itar_pir_m", 						friendly_name = "Доспехи пирата"	 	},
	{ item_instance = "huzvui_itar_bdt_h", 						friendly_name = "Средний меховой доспех"	 	},
	{ item_instance = "huzvui_itar_mil_m", 						friendly_name = "Тяжелые доспехи ополчения"	 	},
	{ item_instance = "huzvui_itar_sld_l", 						friendly_name = "Тяжелый меховой доспех"	 	},
	{ item_instance = "huzvui_itar_djg_crawler", 						friendly_name = "Доспехи из панцирей краулеров"	 	},
	{ item_instance = "huzvui_itar_kdf_l", 						friendly_name = "Мантия мага Огня"	 	},
	{ item_instance = "huzvui_itar_kdw_l", 						friendly_name = "Мантия мага Воды"	 	},
	{ item_instance = "huzvui_stt_armor_h", 						friendly_name = "Доспехи Призрака"	 	},
	{ item_instance = "huzvui_grd_armor_m", 						friendly_name = "Доспех стражника"	 	},
	{ item_instance = "huzvui_org_armor_m", 						friendly_name = "Средние доспехи вора"	 	},
	{ item_instance = "huzvui_org_armor_h", 						friendly_name = "Тяжелые доспехи вора"	 	},
	{ item_instance = "huzvui_tpl_armor_l", 						friendly_name = "Легкие доспехи стража"	 	},
	{ item_instance = "huzvui_grd_armor_i", 						friendly_name = "Доспех королевского стражника"	 	},
	{ item_instance = "huzvui_itar_leather_h", 						friendly_name = "Тяжелый кожаный доспех"	 	},
	{ item_instance = "huzvui_itar_chain_m_01", 						friendly_name = "Укрепленная кольчуга"	 	},
	{ item_instance = "huzvui_itar_chain_m_02", 						friendly_name = "Вороненая кольчуга"	 	},
	{ item_instance = "huzvui_itar_chain_h", 						friendly_name = "Тяжелая вороненая кольчуга"	 	},
	{ item_instance = "huzvui_itar_sth_h", 						friendly_name = "Доспех южанина"	 	},
	{ item_instance = "huzvui_itar_usm_l", 						friendly_name = "Доспех наемного убийцы"	 	},
	{ item_instance = "huzvui_itar_guard_m", 						friendly_name = "Доспехи стражника"	 	},
	{ item_instance = "huzvui_itar_guard_m_renegade", 						friendly_name = "Старые доспехи стражника"	 	},
	{ item_instance = "huzvui_itar_arx_merc", 						friendly_name = "Доспех наемника Араксос"	 	},
	{ item_instance = "huzvui_itar_arx_h1", 						friendly_name = "Доспех следопыта Араксос"	 	},
	{ item_instance = "huzvui_itar_ws_l", 						friendly_name = "Легкий доспех гвардии герцога"	 	},
	{ item_instance = "huzvui_itar_bigben_02", 						friendly_name = "Доспех чемпиона арены"	 	},
	{ item_instance = "huzvui_itar_sld_m", 						friendly_name = "Средние доспехи наемника"	 	},
	{ item_instance = "huzvui_itar_pir_h", 						friendly_name = "Доспех капитана пиратов"	 	},
	{ item_instance = "huzvui_itar_sld_h", 						friendly_name = "Тяжелые доспехи наемника"	 	},
	{ item_instance = "huzvui_itar_pal_m", 						friendly_name = "Доспехи рыцаря"	 	},
	{ item_instance = "huzvui_itar_djg_l", 						friendly_name = "Легкие доспехи охотника на драконов"	 	},
	{ item_instance = "huzvui_grd_armor_h", 						friendly_name = "Тяжелый доспех стражника"	 	},
	{ item_instance = "huzvui_tpl_armor_m", 						friendly_name = "Доспехи Стража"	 	},
	{ item_instance = "huzvui_ebr_armor_m", 						friendly_name = "Доспехи рудного барона"	 	},
	{ item_instance = "huzvui_gur_armor_m", 						friendly_name = "Одеяние Гуру"	 	},
	{ item_instance = "huzvui_kdf_armor_h", 						friendly_name = "Великая мантия мага Огня"	 	},
	{ item_instance = "huzvui_itar_usm_b", 						friendly_name = "Тяжелый доспех наемного убийцы"	 	},
	{ item_instance = "huzvui_itar_crab", 						friendly_name = "Доспех из панцирей краба"	 	},
	{ item_instance = "huzvui_itar_nordmar", 						friendly_name = "Доспех нордмарца"	 	},
	{ item_instance = "huzvui_itar_guard_wm", 						friendly_name = "Тяжелые доспехи стражника"	 	},
	{ item_instance = "huzvui_itar_guard_wm_renegade", 						friendly_name = "Украшенные тяжелые доспехи стражника"	 	},
	{ item_instance = "huzvui_itar_guard_cm", 						friendly_name = "Доспехи стражника-стрелка"	 	},
	{ item_instance = "huzvui_itar_guard_cm_renegade", 						friendly_name = "Старые доспехи стрелка"	 	},
	{ item_instance = "huzvui_itar_arx_w1", 						friendly_name = "Доспех мечника Араксос"	 	},
	{ item_instance = "huzvui_itar_arx_h2", 						friendly_name = "Тяжелый Доспех следопыта Араксос"	 	},
	{ item_instance = "huzvui_itar_ws_m", 						friendly_name = "Доспех гвардии герцога"	 	},
	{ item_instance = "huzvui_itar_pal_h", 						friendly_name = "Доспехи паладина"	 	},
	{ item_instance = "huzvui_itar_djg_m", 						friendly_name = "Средние доспехи Охотника на драконов"	 	},
	{ item_instance = "huzvui_itar_djg_h", 						friendly_name = "Тяжелые доспехи охотника на драконов"	 	},
	{ item_instance = "huzvui_itar_kdf_h", 						friendly_name = "Тяжелая огненная мантия"	 	},
	{ item_instance = "huzvui_itar_kdw_h", 						friendly_name = "Тяжелая мантия мага Воды"	 	},
	{ item_instance = "huzvui_ebr_armor_h", 						friendly_name = "Доспехи верховного Барона"	 	},
	{ item_instance = "huzvui_tpl_armor_h", 						friendly_name = "Тяжелые доспехи Стража"	 	},
	{ item_instance = "huzvui_gur_armor_h", 						friendly_name = "Облачение верховного Гуру"	 	},
	{ item_instance = "huzvui_itar_row_h", 						friendly_name = "Тяжелый доспех Кольца Воды"	 	},
	{ item_instance = "huzvui_itar_royalguard", 						friendly_name = "Доспех королевской гвардии"	 	},
	{ item_instance = "huzvui_itar_knight_01", 						friendly_name = "Роскошный доспех"	 	},
	{ item_instance = "huzvui_itar_knight_02", 						friendly_name = "Позолоченный доспех"	 	},
	{ item_instance = "huzvui_itar_guard_wh", 						friendly_name = "Доспехи капитана стражи"	 	},
	{ item_instance = "huzvui_itar_guard_ch", 						friendly_name = "Тяжелые доспехи стражника-стрелка"	 	},
	{ item_instance = "huzvui_itar_arx_s", 						friendly_name = "Доспех воеводы Араксос"	 	},
	{ item_instance = "huzvui_itar_ulryk", 						friendly_name = "Доспех герцога"	 	},
	{ item_instance = "huzvui_itar_xardas", 						friendly_name = "Мантия черной магии"	 	},
	{ item_instance = "huzvui_itar_dementor", 						friendly_name = "Мантия Тьмы"	 	},
	{ item_instance = "huzvui_itar_raven", 						friendly_name = "Доспехи Тьмы"	 	},
	{ item_instance = "huzvui_itar_mayazombie", 						friendly_name = "Старые доспехи"	 	},
	{ item_instance = "huzvui_itar_pal_skel", 						friendly_name = "Старые рыцарские роспехи"	 	},
	{ item_instance = "huzvui_ore_armor_m", 						friendly_name = "Древние рудные доспехи"	 	},
	{ item_instance = "huzvui_itar_wolfzack", 						friendly_name = "Древний доспех Волчьих Сынов"	 	},
	{ item_instance = "winupp_ithe_ciggy", 						friendly_name = "Сигарета (в зубах)"	 	},
	{ item_instance = "winupp_ithe_blunt", 						friendly_name = "Косяк (в зубах)"	 	},
	{ item_instance = "winupp_ithe_pipe", 						friendly_name = "Трубка (в зубах)"	 	},
	{ item_instance = "winupp_ithe_glasses", 						friendly_name = "Очки"	 	},
	{ item_instance = "winupp_ithe_furcap", 						friendly_name = "Меховая шапочка"	 	},
	{ item_instance = "winupp_ithe_strawhat", 						friendly_name = "Соломенная шляпа"	 	},
	{ item_instance = "winupp_ithe_leathercap", 						friendly_name = "Кожаный чепец"	 	},
	{ item_instance = "winupp_ithe_sack", 						friendly_name = "Мешок с прорезями"	 	},
	{ item_instance = "winupp_ithe_turban", 						friendly_name = "Тюрбан"	 	},
	{ item_instance = "winupp_ithe_mask_01", 						friendly_name = "Коричневая маска"	 	},
	{ item_instance = "winupp_ithe_mask_02", 						friendly_name = "Красная маска"	 	},
	{ item_instance = "winupp_ithe_mask_03", 						friendly_name = "Синяя маска"	 	},
	{ item_instance = "winupp_ithe_mask_04", 						friendly_name = "Маска из мешковины"	 	},
	{ item_instance = "winupp_ithe_mask_05", 						friendly_name = "Серая маска"	 	},
	{ item_instance = "winupp_ithe_mask_06", 						friendly_name = "Черная маска"	 	},
	{ item_instance = "winupp_ithe_guard_exp", 						friendly_name = "Гвардейский морион"	 	},
	{ item_instance = "winupp_ithe_war", 						friendly_name = "Старый железный шлем"	 	},
	{ item_instance = "winupp_ithe_oht", 						friendly_name = "Шлем охотника на демонов"	 	},
	{ item_instance = "winupp_ithe_grd", 						friendly_name = "Церемониальный шлем"	 	},
	{ item_instance = "winupp_ithe_king", 						friendly_name = "Корона Миртаны"	 	},
	{ item_instance = "winupp_ithe_judge", 						friendly_name = "Колпак судьи"	 	},
	{ item_instance = "winupp_ithe_pirate", 						friendly_name = "Треуголка"	 	},
	{ item_instance = "winupp_ithe_pal_m", 						friendly_name = "Кольчужный капюшон"	 	},
	{ item_instance = "winupp_ithe_pal_h", 						friendly_name = "Шлем паладина"	 	},
	{ item_instance = "winupp_ithe_pal_hc", 						friendly_name = "Закрытый шлем паладина"	 	},
	{ item_instance = "winupp_ithe_djg_m", 						friendly_name = "Шлем охотника на драконов"	 	},
	{ item_instance = "winupp_ithe_djg_h", 						friendly_name = "Тяжелый шлем охотника на драконов"	 	},
	{ item_instance = "winupp_ithe_greathelm", 						friendly_name = "Шлем рыцаря"	 	},
	{ item_instance = "winupp_ithe_eisenhut", 						friendly_name = "Айзенхут"	 	},
	{ item_instance = "winupp_ithe_beret_01", 						friendly_name = "Желтый берет"	 	},
	{ item_instance = "winupp_ithe_beret_02", 						friendly_name = "Алый берет"	 	},
	{ item_instance = "winupp_ithe_beret_03", 						friendly_name = "Синий берет"	 	},
	{ item_instance = "winupp_ithe_beret_04", 						friendly_name = "Пурпурный берет"	 	},
	{ item_instance = "winupp_ithe_beret_05", 						friendly_name = "Зеленый берет"	 	},
	{ item_instance = "winupp_ithe_beret_06", 						friendly_name = "Черный берет"	 	},
	{ item_instance = "winupp_ithe_guard", 						friendly_name = "Шапель стражника"	 	},
	{ item_instance = "winupp_ithe_ws_l", 						friendly_name = "Круглый шлем"	 	},
	{ item_instance = "winupp_ithe_ws_h", 						friendly_name = "Круглый шлем с бармицей"	 	},
	{ item_instance = "winupp_ithe_nord_01", 						friendly_name = "Северный шлем с бармицей"	 	},
	{ item_instance = "winupp_ithe_ben_01", 						friendly_name = "Шлем гладиатора"	 	},
	{ item_instance = "winupp_ithe_ben_02", 						friendly_name = "Шлем чемпиона арены"	 	},
	{ item_instance = "mcyzod_itsh_shield_01", 						friendly_name = "Деревянный щит"	 	},
	{ item_instance = "mcyzod_itsh_shield_02", 						friendly_name = "Рыцарский щит"	 	},
	{ item_instance = "mcyzod_itsh_shield_03", 						friendly_name = "Гербовой щит Миртаны"	 	},
	{ item_instance = "mcyzod_itsh_shield_04", 						friendly_name = "Кавалерийский щит"	 	},
	{ item_instance = "mcyzod_itsh_shield_05", 						friendly_name = "Деревянный щит 2"	 	},
	{ item_instance = "mcyzod_itsh_shield_06", 						friendly_name = "Круглый щит"	 	},
	{ item_instance = "gkwqdz_itmw_1h_vlk_dagger", 						friendly_name = "Кинжал"	 	},
	{ item_instance = "gkwqdz_itmw_1h_mace_l_01", 						friendly_name = "Кочерга"	 	},
	{ item_instance = "gkwqdz_itmw_1h_vlk_mace", 						friendly_name = "Трость"	 	},
	{ item_instance = "gkwqdz_itmw_1h_mace_l_03", 						friendly_name = "Дубина"	 	},
	{ item_instance = "gkwqdz_itmw_1h_bau_mace", 						friendly_name = "Тяжелый сук"	 	},
	{ item_instance = "gkwqdz_itmw_1h_vlk_axe", 						friendly_name = "Топорик"	 	},
	{ item_instance = "gkwqdz_itmw_nagelknueppel", 						friendly_name = "Палица с шипами"	 	},
	{ item_instance = "gkwqdz_itmw_1h_sword_l_03", 						friendly_name = "Волчий нож"	 	},
	{ item_instance = "gkwqdz_itmw_1h_misc_sword", 						friendly_name = "Ржавый меч"	 	},
	{ item_instance = "gkwqdz_itmw_sense", 						friendly_name = "Малая коса"	 	},
	{ item_instance = "gkwqdz_itmw_shortsword1", 						friendly_name = "Короткий меч ополчения"	 	},
	{ item_instance = "gkwqdz_itmw_shortsword2", 						friendly_name = "Грубый короткий меч"	 	},
	{ item_instance = "gkwqdz_itmw_1h_vlk_sword", 						friendly_name = "Шпага"	 	},
	{ item_instance = "gkwqdz_itmw_shortsword3", 						friendly_name = "Короткий меч"	 	},
	{ item_instance = "gkwqdz_itmw_nagelkeule", 						friendly_name = "Дубина с шипами"	 	},
	{ item_instance = "gkwqdz_itmw_shortsword4", 						friendly_name = "Волчий зуб"	 	},
	{ item_instance = "gkwqdz_itmw_shortsword5", 						friendly_name = "Изысканный короткий меч"	 	},
	{ item_instance = "gkwqdz_itmw_nagelkeule2", 						friendly_name = "Тяжелая дубина с шипами"	 	},
	{ item_instance = "gkwqdz_itmw_schiffsaxt", 						friendly_name = "Корабельный топор"	 	},
	{ item_instance = "gkwqdz_itmw_finedagger", 						friendly_name = "Хороший кинжал"	 	},
	{ item_instance = "gkwqdz_itmw_addon_pir1haxe", 						friendly_name = "Абордажный топорик"	 	},
	{ item_instance = "gkwqdz_itmw_1h_sld_axe", 						friendly_name = "Грубый тесак"	 	},
	{ item_instance = "gkwqdz_itmw_1h_sld_sword", 						friendly_name = "Грубый меч"	 	},
	{ item_instance = "gkwqdz_itmw_1h_common_01", 						friendly_name = "Простой меч"	 	},
	{ item_instance = "gkwqdz_itmw_1h_mil_sword", 						friendly_name = "Грубый палаш"	 	},
	{ item_instance = "gkwqdz_itmw_addon_pir1hsword", 						friendly_name = "Абордажная сабля"	 	},
	{ item_instance = "gkwqdz_itmw_banditrapier", 						friendly_name = "Рапира бандита"	 	},
	{ item_instance = "gkwqdz_itmw_addon_keule_1h_01", 						friendly_name = "Дубинка ветра"	 	},
	{ item_instance = "gkwqdz_itmw_addon_hacker_1h_01", 						friendly_name = "Мачете"	 	},
	{ item_instance = "gkwqdz_itmw_addon_hacker_1h_02", 						friendly_name = "Старое мачете"	 	},
	{ item_instance = "gkwqdz_itmw_steinbrecher", 						friendly_name = "Дробитель камней"	 	},
	{ item_instance = "gkwqdz_itmw_spicker", 						friendly_name = "Раскалыватель черепов"	 	},
	{ item_instance = "gkwqdz_itmw_schwert", 						friendly_name = "Грубый длинный меч"	 	},
	{ item_instance = "gkwqdz_itmw_schwert1", 						friendly_name = "Изысканный меч"	 	},
	{ item_instance = "gkwqdz_itmw_schwert2", 						friendly_name = "Длинный меч"	 	},
	{ item_instance = "gkwqdz_itmw_schwert3", 						friendly_name = "Грубый полуторный меч"	 	},
	{ item_instance = "gkwqdz_itmw_rubinklinge", 						friendly_name = "Рубиновый клинок"	 	},
	{ item_instance = "gkwqdz_itmw_1h_special_01", 						friendly_name = "Длинный рудный меч"	 	},
	{ item_instance = "gkwqdz_itmw_kriegshammer1", 						friendly_name = "Военный молот"	 	},
	{ item_instance = "gkwqdz_itmw_kriegskeule", 						friendly_name = "Военная булава"	 	},
	{ item_instance = "gkwqdz_itmw_piratensaebel", 						friendly_name = "Пиратская сабля"	 	},
	{ item_instance = "gkwqdz_itmw_streitkolben", 						friendly_name = "Булава"	 	},
	{ item_instance = "gkwqdz_itmw_schwert5", 						friendly_name = "Изысканный полуторный меч"	 	},
	{ item_instance = "gkwqdz_itmw_schwert4", 						friendly_name = "Изысканный длинный меч"	 	},
	{ item_instance = "gkwqdz_itmw_runenschwert", 						friendly_name = "Рунный Меч"	 	},
	{ item_instance = "gkwqdz_itmw_rabenschnabel", 						friendly_name = "Клюв Ворона"	 	},
	{ item_instance = "gkwqdz_itmw_inquisitor", 						friendly_name = "Инквизитор"	 	},
	{ item_instance = "gkwqdz_itmw_rapier", 						friendly_name = "Рапира"	 	},
	{ item_instance = "gkwqdz_itmw_kriegshammer2", 						friendly_name = "Тяжелый военный молот"	 	},
	{ item_instance = "gkwqdz_itmw_morgenstern", 						friendly_name = "Булава с шипами"	 	},
	{ item_instance = "gkwqdz_itmw_doppelaxt", 						friendly_name = "Двойной топор"	 	},
	{ item_instance = "gkwqdz_itmw_bartaxt", 						friendly_name = "Бердыш"	 	},
	{ item_instance = "gkwqdz_itmw_1h_special_02", 						friendly_name = "Полуторный рудный меч"	 	},
	{ item_instance = "gkwqdz_itmw_1h_pal_sword", 						friendly_name = "Офицерский меч"	 	},
	{ item_instance = "gkwqdz_itmw_1h_blessed_01", 						friendly_name = "Грубый рудный клинок"	 	},
	{ item_instance = "gkwqdz_itmw_1h_special_03", 						friendly_name = "Рудный боевой клинок"	 	},
	{ item_instance = "gkwqdz_itmw_elbastardo", 						friendly_name = "Эль-бастардо"	 	},
	{ item_instance = "gkwqdz_itmw_meisterdegen", 						friendly_name = "Шпага мастера"	 	},
	{ item_instance = "gkwqdz_itmw_folteraxt", 						friendly_name = "Топор палача"	 	},
	{ item_instance = "gkwqdz_itmw_orkschlaechter", 						friendly_name = "Убийца орков"	 	},
	{ item_instance = "gkwqdz_itmw_1h_blessed_02", 						friendly_name = "Освященный рудный клинок"	 	},
	{ item_instance = "gkwqdz_itmw_1h_special_04", 						friendly_name = "Рудный клинок Убийца драконов"	 	},
	{ item_instance = "gkwqdz_itmw_1h_blessed_03", 						friendly_name = "Гнев Инноса"	 	},
	{ item_instance = "gkwqdz_itmw_beliarclaw_1h", 						friendly_name = "Коготь Белиара"	 	},
	{ item_instance = "gkwqdz_itmw_pitchfork", 						friendly_name = "Вилы"	 	},
	{ item_instance = "gkwqdz_itmw_2h_nov_staff", 						friendly_name = "Посох послушника"	 	},
	{ item_instance = "gkwqdz_itmw_richtstab", 						friendly_name = "Посох судьи"	 	},
	{ item_instance = "gkwqdz_itmw_rangerstaff_addon", 						friendly_name = "Посох Кольца Воды"	 	},
	{ item_instance = "gkwqdz_itmw_2h_misc_axe", 						friendly_name = "Ржавый топор"	 	},
	{ item_instance = "gkwqdz_itmw_2h_sword_m_01", 						friendly_name = "Ржавый двуручный меч"	 	},
	{ item_instance = "gkwqdz_itmw_zweihaender1", 						friendly_name = "Легкий двуручный меч"	 	},
	{ item_instance = "gkwqdz_itmw_streitaxt1", 						friendly_name = "Легкий боевой топор"	 	},
	{ item_instance = "gkwqdz_itmw_stabkeule", 						friendly_name = "Палица"	 	},
	{ item_instance = "gkwqdz_itmw_hellebarde", 						friendly_name = "Поллэкс"	 	},
	{ item_instance = "gkwqdz_itmw_addon_keule_2h_01", 						friendly_name = "Дубинка бури"	 	},
	{ item_instance = "gkwqdz_itmw_addon_hacker_2h_02", 						friendly_name = "Старое гигантское мачете"	 	},
	{ item_instance = "gkwqdz_itmw_addon_stab01", 						friendly_name = "Посох мага Огня"	 	},
	{ item_instance = "gkwqdz_itmw_addon_stab02", 						friendly_name = "Магический посох"	 	},
	{ item_instance = "gkwqdz_itmw_addon_stab03", 						friendly_name = "Посох мага Воды"	 	},
	{ item_instance = "gkwqdz_itmw_addon_stab04", 						friendly_name = "Посох магистра Огня"	 	},
	{ item_instance = "gkwqdz_itmw_addon_stab05", 						friendly_name = "Тайфун"	 	},
	{ item_instance = "gkwqdz_itmw_2h_sld_axe", 						friendly_name = "Грубый боевой топор"	 	},
	{ item_instance = "gkwqdz_itmw_2h_sld_sword", 						friendly_name = "Грубый двуручный меч"	 	},
	{ item_instance = "gkwqdz_itmw_2h_pal_sword", 						friendly_name = "Двуручный меч паладина"	 	},
	{ item_instance = "gkwqdz_itmw_zweihaender2", 						friendly_name = "Двуручный меч"	 	},
	{ item_instance = "gkwqdz_itmw_streitaxt2", 						friendly_name = "Боевой топор"	 	},
	{ item_instance = "gkwqdz_itmw_zweihaender4", 						friendly_name = "Тяжелый двуручный меч"	 	},
	{ item_instance = "gkwqdz_itmw_schlachtaxt", 						friendly_name = "Военный топор"	 	},
	{ item_instance = "gkwqdz_itmw_addon_hacker_2h_01", 						friendly_name = "Гигантское мачете"	 	},
	{ item_instance = "gkwqdz_itmw_krummschwert", 						friendly_name = "Ятаган"	 	},
	{ item_instance = "gkwqdz_itmw_2h_orcaxe_01", 						friendly_name = "Легкий топор орков"	 	},
	{ item_instance = "gkwqdz_itmw_2h_orcaxe_02", 						friendly_name = "Средний топор орков"	 	},
	{ item_instance = "gkwqdz_itmw_2h_orcsword_01", 						friendly_name = "Ятаган орка"	 	},
	{ item_instance = "gkwqdz_itmw_barbarenstreitaxt", 						friendly_name = "Боевой топор варваров"	 	},
	{ item_instance = "gkwqdz_itmw_addon_pir2haxe", 						friendly_name = "Крушитель досок"	 	},
	{ item_instance = "gkwqdz_itmw_addon_pir2hsword", 						friendly_name = "Тяжелый ятаган"	 	},
	{ item_instance = "gkwqdz_itmw_2h_special_02", 						friendly_name = "Тяжелый рудный двуручник"	 	},
	{ item_instance = "gkwqdz_itmw_2h_blessed_01", 						friendly_name = "Грубый рудный клинок"	 	},
	{ item_instance = "gkwqdz_itmw_2h_blessed_02", 						friendly_name = "Меч Ордена"	 	},
	{ item_instance = "gkwqdz_itmw_sturmbringer", 						friendly_name = "Несущий бурю"	 	},
	{ item_instance = "gkwqdz_itmw_berserkeraxt", 						friendly_name = "Топор берсеркера"	 	},
	{ item_instance = "gkwqdz_itmw_halberd", 						friendly_name = "Алебарда"	 	},
	{ item_instance = "gkwqdz_itmw_2h_orcaxe_03", 						friendly_name = "Тяжелый топор орков"	 	},
	{ item_instance = "gkwqdz_itmw_2h_special_01", 						friendly_name = "Изысканный рудный двуручник"	 	},
	{ item_instance = "gkwqdz_itmw_zweihaender3", 						friendly_name = "Сила рун"	 	},
	{ item_instance = "gkwqdz_itmw_2h_special_03", 						friendly_name = "Мстительная Сталь"	 	},
	{ item_instance = "gkwqdz_itmw_drachenschneide", 						friendly_name = "Гроза драконов"	 	},
	{ item_instance = "gkwqdz_itmw_2h_special_04", 						friendly_name = "Большой рудный Убийца драконов"	 	},
	{ item_instance = "gkwqdz_itmw_2h_blessed_03", 						friendly_name = "Святой палач"	 	},
	{ item_instance = "gkwqdz_itmw_2h_orcaxe_04", 						friendly_name = "Брутальный топор орков"	 	},
	{ item_instance = "gkwqdz_itmw_beliarclaw_2h", 						friendly_name = "Коготь Белиара"	 	},
	{ item_instance = "gkwqdz_itmw_2h_orcsword_02", 						friendly_name = "Военный меч орков"	 	},
	{ item_instance = "eyqtds_itrw_bow_l_01", 						friendly_name = "Короткий лук"	 	},
	{ item_instance = "eyqtds_itrw_bow_l_02", 						friendly_name = "Ивовый лук"	 	},
	{ item_instance = "eyqtds_itrw_sld_bow", 						friendly_name = "Лук наемника"	 	},
	{ item_instance = "eyqtds_itrw_bow_l_03", 						friendly_name = "Охотничий лук"	 	},
	{ item_instance = "eyqtds_itrw_bow_l_04", 						friendly_name = "Вязовый лук"	 	},
	{ item_instance = "eyqtds_itrw_bow_m_01", 						friendly_name = "Композитный лук"	 	},
	{ item_instance = "eyqtds_itrw_bow_m_02", 						friendly_name = "Ясеневый лук"	 	},
	{ item_instance = "eyqtds_itrw_bow_m_03", 						friendly_name = "Длинный лук"	 	},
	{ item_instance = "eyqtds_itrw_bow_m_04", 						friendly_name = "Буковый лук"	 	},
	{ item_instance = "eyqtds_itrw_bow_h_01", 						friendly_name = "Костяной лук"	 	},
	{ item_instance = "eyqtds_itrw_bow_h_02", 						friendly_name = "Дубовый лук"	 	},
	{ item_instance = "eyqtds_itrw_bow_h_03", 						friendly_name = "Военный лук"	 	},
	{ item_instance = "eyqtds_itrw_bow_h_04", 						friendly_name = "Драконий лук"	 	},
	{ item_instance = "eyqtds_itrw_magicbow", 						friendly_name = "Магический лук"	 	},
	{ item_instance = "eyqtds_itrw_firebow", 						friendly_name = "Огненный лук"	 	},
	{ item_instance = "eyqtds_itrw_crossbow_l_01", 						friendly_name = "Охотничий арбалет"	 	},
	{ item_instance = "eyqtds_itrw_crossbow_l_02", 						friendly_name = "Легкий арбалет"	 	},
	{ item_instance = "eyqtds_itrw_mil_crossbow", 						friendly_name = "Арбалет стражи"	 	},
	{ item_instance = "eyqtds_itrw_crossbow_m_01", 						friendly_name = "Арбалет"	 	},
	{ item_instance = "eyqtds_itrw_crossbow_m_02", 						friendly_name = "Военный арбалет"	 	}, 
	{ item_instance = "eyqtds_itrw_crossbow_h_01", 						friendly_name = "Тяжелый арбалет"	 	},
	{ item_instance = "eyqtds_itrw_crossbow_h_02", 						friendly_name = "Осадный арбалет"	 	},
	{ item_instance = "eyqtds_itrw_magiccrossbow", 						friendly_name = "Магический арбалет"	 	},
	{ item_instance = "eyqtds_itrw_bullet", 						friendly_name = "Пуля"	 	},
	{ item_instance = "eyqtds_itrw_pistol_01", 						friendly_name = "Старый пистоль"	 	},
	{ item_instance = "eyqtds_itrw_pistol_02", 						friendly_name = "Украшенный пистоль"	 	},
	{ item_instance = "eyqtds_itrw_pistol_03", 						friendly_name = "Изысканный пистоль"	 	},
	{ item_instance = "eyqtds_itrw_musket_01", 						friendly_name = "Карабин"	 	},
	{ item_instance = "eyqtds_itrw_musket_02", 						friendly_name = "Мушкет"	 	},
	{ item_instance = "eyqtds_itrw_musket_03", 						friendly_name = "Удлиненный мушкет"	 	},
	{ item_instance = "gkwqdz_itmw_pickaxe", 						friendly_name = "Кирка"	 	},
	{ item_instance = "gkwqdz_itmw_lumberjack", 						friendly_name = "Топор дровосека"	 	},
	{ item_instance = "gkwqdz_itmw_huntknife", 						friendly_name = "Нож"	 	},
	{ item_instance = "aixopt_itmi_saw", 						friendly_name = "Пила"	 	},
	{ item_instance = "aixopt_itmi_pan", 						friendly_name = "Сковорода"	 	},
	{ item_instance = "gkwqdz_itmw_1h_mace_l_04", 						friendly_name = "Молот кузнеца"	 	},
	{ item_instance = "gkwqdz_itmw_sickle", 						friendly_name = "Серп"	 	},
	{ item_instance = "aixopt_itmi_fishingrod", 						friendly_name = "Удочка"	 	},
	{ item_instance = "aixopt_itmi_chest_01", 						friendly_name = "Дешевый сундук"	 	},
	{ item_instance = "aixopt_itmi_chest_02", 						friendly_name = "Крепкий сундук"	 	},
	{ item_instance = "aixopt_itmi_chest_03", 						friendly_name = "Роскошный сундук"	 	},
	{ item_instance = "aixopt_itmi_lock", 						friendly_name = "Замок"	 	},
	{ item_instance = "aixopt_itmi_keydummy", 						friendly_name = "Заготовка ключа"	 	},
	{ item_instance = "aixopt_itmi_scoop", 						friendly_name = "Ложка"	 	},
	{ item_instance = "aixopt_itmi_bucket", 						friendly_name = "Ведро"	 	},
	{ item_instance = "aixopt_itmi_needle", 						friendly_name = "Игла"	 	},
	{ item_instance = "aixopt_itmi_scissors", 						friendly_name = "Ножницы"	 	},
	{ item_instance = "aixopt_itmi_stomper", 						friendly_name = "Давилка"	 	},
	{ item_instance = "aixopt_itmi_pliers", 						friendly_name = "Щипцы"	 	},
	{ item_instance = "aixopt_itmi_dye", 						friendly_name = "Краситель"	 	},
	{ item_instance = "aixopt_itmi_runeblank", 						friendly_name = "Рунный камень"	 	},
	{ item_instance = "aixopt_itmi_flask", 						friendly_name = "Мензурка"	 	},
	{ item_instance = "aixopt_itmi_paper", 						friendly_name = "Бумага"	 	},
	{ item_instance = "aixopt_itmi_alchemy_quicksilver", 						friendly_name = "Ртуть"	 	},
	{ item_instance = "aixopt_itmi_alchemy_salt", 						friendly_name = "Соль"	 	},
	{ item_instance = "aixopt_itmi_alchemy_syrianoil", 						friendly_name = "Масло"	 	},
	{ item_instance = "aixopt_itmi_alchemy_alcohol", 						friendly_name = "Чистый спирт"	 	},
	{ item_instance = "aixopt_itmi_sulfur", 						friendly_name = "Сера"	 	},
	{ item_instance = "aixopt_itmi_quartz", 						friendly_name = "Ледяной кварц"	 	},
	{ item_instance = "aixopt_itmi_rockcrystal", 						friendly_name = "Горный хрусталь"	 	},
	{ item_instance = "aixopt_itmi_aquamarine", 						friendly_name = "Аквамарин"	 	},
	{ item_instance = "aixopt_itmi_holywater", 						friendly_name = "Святая вода"	 	},
	{ item_instance = "aixopt_itmi_darkpearl", 						friendly_name = "Черный жемчуг"	 	},
	{ item_instance = "aixopt_itmirawsteel", 						friendly_name = "Сырая сталь"	 	},
	{ item_instance = "aixopt_itmi_goldnugget", 						friendly_name = "Золотой самородок"	 	},
	{ item_instance = "aixopt_itmi_silvernugget", 						friendly_name = "Серебряный самородок"	 	},
	{ item_instance = "aixopt_itmi_orenugget", 						friendly_name = "Кусок магической руды"	 	},
	{ item_instance = "aixopt_itmi_oreshards", 						friendly_name = "Рудная крошка"	 	},
	{ item_instance = "aixopt_itmi_ironnugget", 						friendly_name = "Кусок железной руды"	 	},
	{ item_instance = "aixopt_itmi_ironingot", 						friendly_name = "Железный слиток"	 	},
	{ item_instance = "aixopt_itmi_goldingot", 						friendly_name = "Золотой слиток"	 	},
	{ item_instance = "aixopt_itmi_oreingot", 						friendly_name = "Рудный слиток"	 	},
	{ item_instance = "aixopt_itmi_coal", 						friendly_name = "Уголь"	 	},
	{ item_instance = "aixopt_itmi_rawwood", 						friendly_name = "Древесина"	 	},
	{ item_instance = "aixopt_itmi_craftwood", 						friendly_name = "Обработанная древесина"	 	},
	{ item_instance = "aixopt_itmi_blackwood", 						friendly_name = "Черное дерево"	 	},
	{ item_instance = "aixopt_itmi_pitch", 						friendly_name = "Смола"	 	},
	{ item_instance = "aixopt_itmi_linen", 						friendly_name = "Ткань"	 	},
	{ item_instance = "aixopt_itmi_silk", 						friendly_name = "Шелк"	 	},
	{ item_instance = "aixopt_itmi_wool", 						friendly_name = "Шерсть"	 	},
	{ item_instance = "aixopt_itmi_rubin", 						friendly_name = "Рубин"	 	},
	{ item_instance = "aixopt_itmi_skin", 						friendly_name = "Кожа"	 	},
	{ item_instance = "aixopt_itmi_fineskin", 						friendly_name = "Качественная кожа"	 	},
	{ item_instance = "aixopt_itmi_rivetskin", 						friendly_name = "Клепаная кожа"	 	},
	{ item_instance = "aixopt_itmi_tannedskin", 						friendly_name = "Дубленая кожа"	 	},
	{ item_instance = "aixopt_itmi_rivet", 						friendly_name = "Заклепка"	 	},
	{ item_instance = "aixopt_itmi_tanning", 						friendly_name = "Состав для дубления кожи"	 	},
	{ item_instance = "aixopt_itmi_glue", 						friendly_name = "Клей"	 	},
	{ item_instance = "aixopt_itmi_handle", 						friendly_name = "Рукоять"	 	},
	{ item_instance = "aixopt_itmi_linkage", 						friendly_name = "Рычажный механизм"	 	},
	{ item_instance = "aixopt_itmi_acid", 						friendly_name = "Кислота"	 	},
	{ item_instance = "aixopt_itat_wolffur", 						friendly_name = "Волчья шкура"	 	},
	{ item_instance = "aixopt_itat_lurkerskin", 					friendly_name = "Шкура рептилии"	 	},
	{ item_instance = "aixopt_itat_wargfur", 						friendly_name = "Шкура варга"	 	},
	{ item_instance = "aixopt_itat_keilerfur", 						friendly_name = "Шкура кабана"	 	},
	{ item_instance = "aixopt_itat_shadowfur", 						friendly_name = "Шкура мракориса"	 	},
	{ item_instance = "aixopt_itat_sharkskin", 						friendly_name = "Шкура болотной акулы"	 	},
	{ item_instance = "aixopt_itat_trollfur", 						friendly_name = "Шкура тролля"	 	},
	{ item_instance = "aixopt_itat_trollblackfur", 					friendly_name = "Шкура черного тролля"	 	},
	{ item_instance = "aixopt_itat_waranfiretongue", 				friendly_name = "Огненный язык"	 	},
	{ item_instance = "aixopt_itat_sharkteeth", 					friendly_name = "Зубы болотной акулы"	 	},
	{ item_instance = "aixopt_itat_sting", 						friendly_name = "Жало"	 	},
	{ item_instance = "aixopt_itat_wing", 						friendly_name = "Крылья"	 	},
	{ item_instance = "aixopt_itat_bugmandibles", 				friendly_name = "Мандибулы полевого хищника"	 	},
	{ item_instance = "aixopt_itat_skeletonbone", 				friendly_name = "Мандибулы полевого хищника"	 	},
	{ item_instance = "aixopt_itat_crawlermandibles", 				friendly_name = "Мандибулы ползуна"	 	},
	{ item_instance = "aixopt_itmi_alchbasis", 				friendly_name = "Алхимическая основа"	 	},
	{ item_instance = "aixopt_itmi_alchsub", 				friendly_name = "Алхимический субстрат"	 	},
	{ item_instance = "aixopt_itmi_wheat", 						friendly_name = "Зерно"	 	},
	{ item_instance = "aixopt_itmi_spice", 						friendly_name = "Пряности"	 	},
	{ item_instance = "aixopt_itmi_coffee", 						friendly_name = "Кофейные зерна"	 	},
	{ item_instance = "aixopt_itmi_jewelery", 						friendly_name = "Бижутерия"	 	},
	{ item_instance = "aixopt_itmi_gemstones", 						friendly_name = "Драгоценные камни"	 	},
	{ item_instance = "aixopt_itmi_sugarcane", 						friendly_name = "Сахарный тростник"	 	},
	{ item_instance = "aixopt_itmi_wedel", 						friendly_name = "Опахало"	 	},
	{ item_instance = "aixopt_itmi_joint_1", 						friendly_name = "Зеленый послушник"	 	},
	{ item_instance = "aixopt_itmi_joint_2", 						friendly_name = "Северный темный"	 	},
	{ item_instance = "aixopt_itmi_joint_3", 						friendly_name = "Зов мечты"	 	},
	{ item_instance = "aixopt_itmi_stuff_pipe", 						friendly_name = "Трубка"	 	},
	{ item_instance = "aixopt_itmi_stuff_barbknife", 						friendly_name = "Опасная бритва"	 	},
	{ item_instance = "aixopt_itmi_stuff_plate", 						friendly_name = "Тарелка"	 	},
	{ item_instance = "aixopt_itmi_stuff_candel", 						friendly_name = "Подсвечник"	 	},
	{ item_instance = "aixopt_itmi_stuff_cup_01", 						friendly_name = "Кубок"	 	},
	{ item_instance = "aixopt_itmi_stuff_cup_02", 						friendly_name = "Бокал"	 	},
	{ item_instance = "aixopt_itmi_stuff_silverware", 						friendly_name = "Столовый набор"	 	},
	{ item_instance = "aixopt_itmi_stuff_mug", 						friendly_name = "Кружка"	 	},
	{ item_instance = "aixopt_itmi_stuff_amphore", 						friendly_name = "Амфора"	 	},
	{ item_instance = "aixopt_itmi_stuff_idol", 						friendly_name = "Статуэтка Спящего"	 	},
	{ item_instance = "itlstorch", 								friendly_name = "Факел"	 	},
	{ item_instance = "aixopt_itmi_broom", 						friendly_name = "Метла"	 	},
	{ item_instance = "aixopt_itmi_lute", 						friendly_name = "Лютня"	 	},
	{ item_instance = "aixopt_itmi_brush", 						friendly_name = "Щетка"	 	},
	{ item_instance = "aixopt_itmi_joint", 						friendly_name = "Самокрутка с табаком"	 	},
	{ item_instance = "aixopt_itmi_packet", 						friendly_name = "Пакет"	 	},
	{ item_instance = "aixopt_itmi_pocket", 						friendly_name = "Кожаный кошелек"	 	},
	{ item_instance = "aixopt_itmi_oldcoin", 						friendly_name = "Старая монета"	 	},
	{ item_instance = "aixopt_itmi_goldcandleholder", 						friendly_name = "Золотой подсвечник"	 	},
	{ item_instance = "aixopt_itmi_silvercandleholder", 						friendly_name = "Серебряный подсвечник"	 	},
	{ item_instance = "aixopt_itmi_goldnecklace", 						friendly_name = "Золотое ожерелье"	 	},
	{ item_instance = "aixopt_itmi_silvernecklace", 						friendly_name = "Серебряное ожерелье"	 	},
	{ item_instance = "aixopt_itmi_silverring", 						friendly_name = "Серебряное кольцо"	 	},
	{ item_instance = "aixopt_itmi_silvercup", 						friendly_name = "Серебряный кубок"	 	},
	{ item_instance = "aixopt_itmi_silverplate", 						friendly_name = "Серебряная тарелка"	 	},
	{ item_instance = "aixopt_itmi_goldplate", 						friendly_name = "Золотая тарелка"	 	},
	{ item_instance = "aixopt_itmi_goldcup", 						friendly_name = "Золотой кубок"	 	},
	{ item_instance = "aixopt_itmi_bloodcup", 						friendly_name = "Кровавый кубок"	 	},
	{ item_instance = "aixopt_itmi_goldring", 						friendly_name = "Золотое кольцо"	 	},
	{ item_instance = "aixopt_itmi_silverchalice", 						friendly_name = "Серебряная чаша"	 	},
	{ item_instance = "aixopt_itmi_jewelerychest", 						friendly_name = "Шкатулка с драгоценностями"	 	},
	{ item_instance = "aixopt_itmi_goldchalice", 						friendly_name = "Золотая чаша"	 	},
	{ item_instance = "aixopt_itmi_goldchest", 						friendly_name = "Шкатулка"	 	},
	{ item_instance = "aixopt_itmi_innosstatue", 						friendly_name = "Статуэтка Инноса"	 	},
	{ item_instance = "aixopt_itmi_sextant", 						friendly_name = "Секстант"	 	},
	{ item_instance = "aixopt_itmi_apfeltabak", 						friendly_name = "Яблочный табак"	 	},
	{ item_instance = "aixopt_itmi_pilztabak", 						friendly_name = "Грибной табак"	 	},
	{ item_instance = "aixopt_itmi_doppeltabak", 						friendly_name = "Двойное яблоко"	 	},
	{ item_instance = "aixopt_itmi_honigtabak", 						friendly_name = "Медовый табак"	 	},
	{ item_instance = "aixopt_itmi_sumpftabak", 						friendly_name = "Травяной табак"	 	},
	{ item_instance = "aixopt_itat_fat", 						friendly_name = "Жир кротокрыса"	 	},
	{ item_instance = "uhaxlk_itfo_soup", 						friendly_name = "Суп из кореньев"	 	},
	{ item_instance = "uhaxlk_itfo_meatbugragout", 				friendly_name = "Рагу из жуков"	 	},
	{ item_instance = "uhaxlk_itfo_crawlersoup", 				friendly_name = "Суп с мясом ползунов"	 	},
	{ item_instance = "uhaxlk_itat_meatbugflesh", 				friendly_name = "Мясо жука"	 	},
	{ item_instance = "uhaxlk_itat_clamflesh", 				friendly_name = "Моллюск"	 	},
	{ item_instance = "aixopt_itmi_whitepearl", 				friendly_name = "Жемчужина"	 	},
	{ item_instance = "aixopt_itmi_flour", 						friendly_name = "Мука"	 	},
	{ item_instance = "aixopt_itmi_dough", 						friendly_name = "Тесто"	 	},
	{ item_instance = "uhaxlk_itfo_egg", 						friendly_name = "Яйцо"	 	},
	{ item_instance = "uhaxlk_itfo_fish", 						friendly_name = "Сырая рыба"	 	},
	{ item_instance = "uhaxlk_itfo_rawmeat", 						friendly_name = "Сырое мясо"	 	},
	{ item_instance = "uhaxlk_itfo_water", 						friendly_name = "Вода"	 	},
	{ item_instance = "uhaxlk_itfo_milk", 						friendly_name = "Молоко"	 	},
	{ item_instance = "uhaxlk_itfo_apple", 						friendly_name = "Яблоко"	 	},
	{ item_instance = "uhaxlk_itfo_honey", 						friendly_name = "Мед"	 	},
	{ item_instance = "aixopt_itmi_honeycomb", 						friendly_name = "Соты"	 	},
	{ item_instance = "uhaxlk_itfo_wineberry", 						friendly_name = "Виноград"	 	},
	{ item_instance = "uhaxlk_itfo_bread", 						friendly_name = "Хлеб"	 	},
	{ item_instance = "uhaxlk_itfo_cheese", 						friendly_name = "Сыр"	 	},
	{ item_instance = "uhaxlk_itfo_friedmeat", 						friendly_name = "Жареное мясо"	 	},
	{ item_instance = "uhaxlk_itfo_friedfish", 						friendly_name = "Жареная рыба"	 	},
	{ item_instance = "uhaxlk_itfo_stew", 						friendly_name = "Похлебка"	 	},
	{ item_instance = "uhaxlk_itfo_fishsoup", 						friendly_name = "Уха"	 	},
	{ item_instance = "uhaxlk_itfo_beer", 						friendly_name = "Пиво"	 	},
	{ item_instance = "uhaxlk_itfo_booze", 						friendly_name = "Джин"	 	},
	{ item_instance = "uhaxlk_itfo_wine", 						friendly_name = "Вино"	 	},
	{ item_instance = "uhaxlk_itfo_rum", 						friendly_name = "Ром"	 	},
	{ item_instance = "uhaxlk_itfo_bacon", 						friendly_name = "Окорок"	 	},
	{ item_instance = "uhaxlk_itfo_sausage", 						friendly_name = "Колбаса"	 	},
	{ item_instance = "uhaxlk_itfo_meatpie", 						friendly_name = "Мясной пирог"	 	},
	{ item_instance = "uhaxlk_itfo_applepie", 						friendly_name = "Яблочный пирог"	 	},
	{ item_instance = "uhaxlk_itfo_fishpie", 						friendly_name = "Рыбный пирог"	 	},
	{ item_instance = "uhaxlk_itfo_spicysteak", 						friendly_name = "Пикантный стейк"	 	},
	{ item_instance = "uhaxlk_itfo_spicywine", 						friendly_name = "Пряное вино"	 	},
	{ item_instance = "uhaxlk_itfo_spicyfish", 						friendly_name = "Пикантная рыба"	 	},
	{ item_instance = "uhaxlk_itfo_cider", 						friendly_name = "Сидр"	 	},
	{ item_instance = "uhaxlk_itfo_sweetroll", 						friendly_name = "Сладкий рулет"	 	},
	{ item_instance = "uhaxlk_itfo_smallpies", 						friendly_name = "Пирожки"	 	},
	{ item_instance = "uhaxlk_itfo_coffee", 						friendly_name = "Кофе"	 	},
	{ item_instance = "uhaxlk_itfo_applejuice", 						friendly_name = "Яблочный сок"	 	},
	{ item_instance = "uhaxlk_itfo_vodka", 						friendly_name = "Водка"	 	},
	{ item_instance = "cjcpgp_itpo_poison_kill", 						friendly_name = "Яд"	 	},
	{ item_instance = "cjcpgp_itpo_poison_sleep", 						friendly_name = "Снотворное"	 	},
	{ item_instance = "cjcpgp_itpo_antidote", 						friendly_name = "Противоядие"	 	},
	{ item_instance = "cjcpgp_itpo_mana_01", 						friendly_name = "Эссенция маны"	 	},
	{ item_instance = "cjcpgp_itpo_mana_02", 						friendly_name = "Экстракт маны"	 	},
	{ item_instance = "cjcpgp_itpo_mana_03", 						friendly_name = "Эликсир маны"	 	},
	{ item_instance = "cjcpgp_itpo_mana_04", 						friendly_name = "Чистая мана"	 	},
	{ item_instance = "cjcpgp_itpo_health_01", 						friendly_name = "Лечебная эссенция"	 	},
	{ item_instance = "cjcpgp_itpo_health_02", 						friendly_name = "Лечебный экстракт"	 	},
	{ item_instance = "cjcpgp_itpo_health_03", 						friendly_name = "Лечебный эликсир"	 	},
	{ item_instance = "cjcpgp_itpo_health_04", 						friendly_name = "Чистое здоровье"	 	},
	{ item_instance = "cjcpgp_itpo_speed", 						friendly_name = "Зелье ускорения"	 	},
	{ item_instance = "uhaxlk_itfo_fish_kill", 						friendly_name = "Сырая рыба"	 	},
	{ item_instance = "uhaxlk_itfo_rawmeat_kill", 						friendly_name = "Сырое мясо"	 	},
	{ item_instance = "uhaxlk_itfo_water_kill", 						friendly_name = "Вода"	 	},
	{ item_instance = "uhaxlk_itfo_milk_kill", 						friendly_name = "Молоко"	 	},
	{ item_instance = "uhaxlk_itfo_apple_kill", 						friendly_name = "Яблоко"	 	},
	{ item_instance = "uhaxlk_itfo_honey_kill", 						friendly_name = "Мед"	 	},
	{ item_instance = "uhaxlk_itfo_wineberry_kill", 						friendly_name = "Виноград"	 	},
	{ item_instance = "uhaxlk_itfo_bread_kill", 						friendly_name = "Хлеб"	 	},
	{ item_instance = "uhaxlk_itfo_cheese_kill", 						friendly_name = "Сыр"	 	},
	{ item_instance = "uhaxlk_itfo_friedmeat_kill", 						friendly_name = "Жареное мясо"	 	},
	{ item_instance = "uhaxlk_itfo_friedfish_kill", 						friendly_name = "Жареная рыба"	 	},
	{ item_instance = "uhaxlk_itfo_stew_kill", 						friendly_name = "Похлебка"	 	},
	{ item_instance = "uhaxlk_itfo_fishsoup_kill", 						friendly_name = "Уха"	 	},
	{ item_instance = "uhaxlk_itfo_beer_kill", 						friendly_name = "Пиво"	 	},
	{ item_instance = "uhaxlk_itfo_booze_kill", 						friendly_name = "Джин"	 	},
	{ item_instance = "uhaxlk_itfo_wine_kill", 						friendly_name = "Вино"	 	},
	{ item_instance = "uhaxlk_itfo_rum_kill", 						friendly_name = "Ром"	 	},
	{ item_instance = "uhaxlk_itfo_bacon_kill", 						friendly_name = "Окорок"	 	},
	{ item_instance = "uhaxlk_itfo_sausage_kill", 						friendly_name = "Колбаса"	 	},
	{ item_instance = "uhaxlk_itfo_meatpie_kill", 						friendly_name = "Мясной пирог"	 	},
	{ item_instance = "uhaxlk_itfo_applepie_kill", 						friendly_name = "Яблочный пирог"	 	},
	{ item_instance = "uhaxlk_itfo_fishpie_kill", 						friendly_name = "Рыбный пирог"	 	},
	{ item_instance = "uhaxlk_itfo_spicysteak_kill", 						friendly_name = "Пикантный стейк"	 	},
	{ item_instance = "uhaxlk_itfo_spicywine_kill", 						friendly_name = "Пряное вино"	 	},
	{ item_instance = "uhaxlk_itfo_spicyfish_kill", 						friendly_name = "Пикантная рыба"	 	},
	{ item_instance = "uhaxlk_itfo_cider_kill", 						friendly_name = "Сидр"	 	},
	{ item_instance = "uhaxlk_itfo_sweetroll_kill", 						friendly_name = "Сладкий рулет"	 	},
	{ item_instance = "uhaxlk_itfo_smallpies_kill", 						friendly_name = "Пирожки"	 	},
	{ item_instance = "uhaxlk_itfo_coffee_kill", 						friendly_name = "Кофе"	 	},
	{ item_instance = "uhaxlk_itfo_applejuice_kill", 						friendly_name = "Яблочный сок"	 	},
	{ item_instance = "uhaxlk_itfo_vodka_kill", 						friendly_name = "Водка"	 	},
	{ item_instance = "uhaxlk_itfo_fish_sleep", 						friendly_name = "Сырая сыба"	 	},
	{ item_instance = "uhaxlk_itfo_rawmeat_sleep", 						friendly_name = "Сырое мясо"	 	},
	{ item_instance = "uhaxlk_itfo_water_sleep", 						friendly_name = "Вода"	 	},
	{ item_instance = "uhaxlk_itfo_milk_sleep", 						friendly_name = "Молоко"	 	},
	{ item_instance = "uhaxlk_itfo_apple_sleep", 						friendly_name = "Яблоко"	 	},
	{ item_instance = "uhaxlk_itfo_honey_sleep", 						friendly_name = "Мед"	 	},
	{ item_instance = "uhaxlk_itfo_wineberry_sleep", 						friendly_name = "Виноград"	 	},
	{ item_instance = "uhaxlk_itfo_bread_sleep", 						friendly_name = "Хлеб"	 	},
	{ item_instance = "uhaxlk_itfo_cheese_sleep", 						friendly_name = "Сыр"	 	},
	{ item_instance = "uhaxlk_itfo_friedmeat_sleep", 						friendly_name = "Жареное мясо"	 	},
	{ item_instance = "uhaxlk_itfo_friedfish_sleep", 						friendly_name = "Жареная рыба"	 	},
	{ item_instance = "uhaxlk_itfo_stew_sleep", 						friendly_name = "Похлебка"	 	},
	{ item_instance = "uhaxlk_itfo_fishsoup_sleep", 						friendly_name = "Уха"	 	},
	{ item_instance = "uhaxlk_itfo_beer_sleep", 						friendly_name = "Пиво"	 	},
	{ item_instance = "uhaxlk_itfo_booze_sleep", 						friendly_name = "Джин"	 	},
	{ item_instance = "uhaxlk_itfo_wine_sleep", 						friendly_name = "Вино"	 	},
	{ item_instance = "uhaxlk_itfo_rum_sleep", 						friendly_name = "Ром"	 	},
	{ item_instance = "uhaxlk_itfo_bacon_sleep", 						friendly_name = "Окорок"	 	},
	{ item_instance = "uhaxlk_itfo_sausage_sleep", 						friendly_name = "Колбаса"	 	},
	{ item_instance = "uhaxlk_itfo_meatpie_sleep", 						friendly_name = "Мясной пирог"	 	},
	{ item_instance = "uhaxlk_itfo_applepie_sleep", 						friendly_name = "Яблочный пирог"	 	},
	{ item_instance = "uhaxlk_itfo_fishpie_sleep", 						friendly_name = "Рыбный пирог"	 	},
	{ item_instance = "uhaxlk_itfo_spicysteak_sleep", 						friendly_name = "Пикантный стейк"	 	},
	{ item_instance = "uhaxlk_itfo_spicywine_sleep", 						friendly_name = "Пряное вино"	 	},
	{ item_instance = "uhaxlk_itfo_spicyfish_sleep", 						friendly_name = "Пикантная рыба"	 	},
	{ item_instance = "uhaxlk_itfo_cider_sleep", 						friendly_name = "Сидр"	 	},
	{ item_instance = "uhaxlk_itfo_sweetroll_sleep", 						friendly_name = "Сладкий рулет"	 	},
	{ item_instance = "uhaxlk_itfo_smallpies_sleep", 						friendly_name = "Пирожки"	 	},
	{ item_instance = "uhaxlk_itfo_coffee_sleep", 						friendly_name = "Кофе"	 	},
	{ item_instance = "uhaxlk_itfo_applejuice_sleep", 						friendly_name = "Яблочный сок"	 	},
	{ item_instance = "uhaxlk_itfo_vodka_sleep", 						friendly_name = "Водка"	 	},
	{ item_instance = "hymyrk_itsc_armyofdarkness", 						friendly_name = "Армия тьмы"	 	},
	{ item_instance = "hymyrk_itsc_breathofdeath", 						friendly_name = "Дыхание смерти"	 	},
	{ item_instance = "hymyrk_itsc_massdeath", 						friendly_name = "Волна смерти"	 	},
	{ item_instance = "hymyrk_itsc_firebolt", 						friendly_name = "Огненная стрела"	 	},
	{ item_instance = "hymyrk_itsc_instantfireball", 						friendly_name = "Огненный шар"	 	},
	{ item_instance = "hymyrk_itsc_firestorm", 						friendly_name = "Малая огненная буря"	 	},
	{ item_instance = "hymyrk_itsc_chargefireball", 						friendly_name = "Большой бгненный шар"	 	},
	{ item_instance = "hymyrk_itsc_pyrokinesis", 						friendly_name = "Большая огненная буря"	 	},
	{ item_instance = "hymyrk_itsc_firerain", 						friendly_name = "Огненный дождь"	 	},
	{ item_instance = "hymyrk_itsc_icebolt", 						friendly_name = "Ледяная стрела"	 	},
	{ item_instance = "hymyrk_itsc_waterfist", 						friendly_name = "Кулак воды"	 	},
	{ item_instance = "hymyrk_itsc_whirlwind", 						friendly_name = "Смерч"	 	},
	{ item_instance = "hymyrk_itsc_windfist", 						friendly_name = "Кулак ветра"	 	},
	{ item_instance = "hymyrk_itsc_zap", 						friendly_name = "Малая молния"	 	},
	{ item_instance = "hymyrk_itsc_lightningflash", 						friendly_name = "Молния"	 	},
	{ item_instance = "hymyrk_itsc_geyser", 						friendly_name = "Гейзер"	 	},
	{ item_instance = "hymyrk_itsc_thunderball", 						friendly_name = "Шаровая молния"	 	},
	{ item_instance = "hymyrk_itsc_icecube", 						friendly_name = "Ледяной блок"	 	},
	{ item_instance = "hymyrk_itsc_icelance", 						friendly_name = "Ледяное копье"	 	},
	{ item_instance = "hymyrk_itsc_thunderstorm", 						friendly_name = "Буря"	 	},
	{ item_instance = "hymyrk_itsc_icewave", 						friendly_name = "Ледяная волна"	 	},
	{ item_instance = "hymyrk_itsc_light", 						friendly_name = "Свет"	 	},
	{ item_instance = "hymyrk_itsc_lightheal", 						friendly_name = "Лечение легких ранений"	 	},
	{ item_instance = "hymyrk_itsc_mediumheal", 						friendly_name = "Лечение средних ранений"	 	},
	{ item_instance = "hymyrk_itsc_fullheal", 						friendly_name = "Лечение тяжелых ранений"	 	},
	{ item_instance = "hymyrk_itsc_paldestroyevil", 						friendly_name = "Уничтожение зла"	 	},
	{ item_instance = "hymyrk_itsc_palfullheal", 						friendly_name = "Большое исцеление"	 	},
	{ item_instance = "hymyrk_itsc_palholybolt", 						friendly_name = "Святая стрела"	 	},
	{ item_instance = "hymyrk_itsc_pallight", 						friendly_name = "Святой свет"	 	},
	{ item_instance = "hymyrk_itsc_pallightheal", 						friendly_name = "Малое исцеление"	 	},
	{ item_instance = "hymyrk_itsc_palmediumheal", 						friendly_name = "Среднее исцеление"	 	},
	{ item_instance = "hymyrk_itsc_palrepelevil", 						friendly_name = "Изгнание зла"	 	},
	{ item_instance = "hymyrk_itsc_shrink", 						friendly_name = "Уменьшение монстра"	 	},
	{ item_instance = "hymyrk_itsc_sleep", 						friendly_name = "Сон"	 	},
	{ item_instance = "hymyrk_itsc_sumdemon", 						friendly_name = "Вызов демона"	 	},
	{ item_instance = "hymyrk_itsc_sumgobskel", 						friendly_name = "Вызов скелета гоблина"	 	},
	{ item_instance = "hymyrk_itsc_sumgol", 						friendly_name = "Вызов голема"	 	},
	{ item_instance = "hymyrk_itsc_sumskel", 						friendly_name = "Вызов скелета"	 	},
	{ item_instance = "hymyrk_itsc_sumwolf", 						friendly_name = "Вызов волка"	 	},
	{ item_instance = "hymyrk_itsc_trfdragonsnapper", 						friendly_name = "Превращение В драконьего снеппера"	 	},
	{ item_instance = "hymyrk_itsc_trffirewaran", 						friendly_name = "Превращение В огненного ящера"	 	},
	{ item_instance = "hymyrk_itsc_trfgiantbug", 						friendly_name = "Превращение В полевого хищника"	 	},
	{ item_instance = "hymyrk_itsc_trfgiantrat", 						friendly_name = "Превращение В гигантскую крысу"	 	},
	{ item_instance = "hymyrk_itsc_trflurker", 						friendly_name = "Превращение В луркера"	 	},
	{ item_instance = "hymyrk_itsc_trfscavenger", 						friendly_name = "Превращение В падальщика"	 	},
	{ item_instance = "hymyrk_itsc_trfshadowbeast", 						friendly_name = "Превращение в мракориса"	 	},
	{ item_instance = "hymyrk_itsc_trfsheep", 						friendly_name = "Превращение в овцу"	 	},
	{ item_instance = "hymyrk_itsc_trfsnapper", 						friendly_name = "Превращение в снеппера"	 	},
	{ item_instance = "hymyrk_itsc_trfwaran", 						friendly_name = "Превращение в ящера"	 	},
	{ item_instance = "hymyrk_itsc_trfwarg", 						friendly_name = "Превращение в варга"	 	},
	{ item_instance = "hymyrk_itsc_trfwolf", 						friendly_name = "Превращение в волка"	 	},
	{ item_instance = "xthmqe_itru_armyofdarkness", 						friendly_name = "Армия тьмы"	 	},
	{ item_instance = "xthmqe_itru_beliarsrage", 						friendly_name = "Гнев Белиара"	 	},
	{ item_instance = "xthmqe_itru_breathofdeath", 						friendly_name = "Дыхание смерти"	 	},
	{ item_instance = "xthmqe_itru_deathball", 						friendly_name = "Шар тьмы"	 	},
	{ item_instance = "xthmqe_itru_deathbolt", 						friendly_name = "Стрела тьмы"	 	},
	{ item_instance = "xthmqe_itru_fear", 						friendly_name = "Страх"	 	},
	{ item_instance = "xthmqe_itru_massdeath", 						friendly_name = "Волна смерти"	 	},
	{ item_instance = "xthmqe_itru_skull", 						friendly_name = "Крик смерти"	 	},
	{ item_instance = "xthmqe_itru_suckenergy", 						friendly_name = "Кража энергии"	 	},
	{ item_instance = "xthmqe_itru_greententacle", 						friendly_name = "Корень-ловушка"	 	},
	{ item_instance = "xthmqe_itru_swarm", 						friendly_name = "Рой насекомых"	 	},
	{ item_instance = "xthmqe_itru_concussionbolt", 						friendly_name = "Стрела сотрясения"	 	},
	{ item_instance = "xthmqe_itru_chargefireball", 						friendly_name = "Большой огненный шар"	 	},
	{ item_instance = "xthmqe_itru_firebolt", 						friendly_name = "Огненная стрела"	 	},
	{ item_instance = "xthmqe_itru_firerain", 						friendly_name = "Огненный дождь"	 	},
	{ item_instance = "xthmqe_itru_firestorm", 						friendly_name = "Малая огненная буря"	 	},
	{ item_instance = "xthmqe_itru_instantfireball", 						friendly_name = "Огненный шар"	 	},
	{ item_instance = "xthmqe_itru_pyrokinesis", 						friendly_name = "Большая огненная буря"	 	},
	{ item_instance = "xthmqe_itru_icebolt", 						friendly_name = "Ледяная стрела"	 	},
	{ item_instance = "xthmqe_itru_icecube", 						friendly_name = "Ледяной блок"	 	},
	{ item_instance = "xthmqe_itru_icelance", 						friendly_name = "Ледяное копье"	 	},
	{ item_instance = "xthmqe_itru_icewave", 						friendly_name = "Ледяная волна"	 	},
	{ item_instance = "xthmqe_itru_geyser", 						friendly_name = "Гейзер"	 	},
	{ item_instance = "xthmqe_itru_lightningflash", 						friendly_name = "Молния"	 	},
	{ item_instance = "xthmqe_itru_thunderball", 						friendly_name = "Шаровая молния"	 	},
	{ item_instance = "xthmqe_itru_thunderstorm", 						friendly_name = "Буря"	 	},
	{ item_instance = "xthmqe_itru_waterfist", 						friendly_name = "Кулак воды"	 	},
	{ item_instance = "xthmqe_itru_whirlwind", 						friendly_name = "Смерч"	 	},
	{ item_instance = "xthmqe_itru_windfist", 						friendly_name = "Кулак ветра"	 	},
	{ item_instance = "xthmqe_itru_zap", 						friendly_name = "Малая молния"	 	},
	{ item_instance = "xthmqe_itru_light", 						friendly_name = "Свет"	 	},
	{ item_instance = "xthmqe_itru_lightheal", 						friendly_name = "Лечение легких ранений"	 	},
	{ item_instance = "xthmqe_itru_mediumheal", 						friendly_name = "Лечение средних ранений"	 	},
	{ item_instance = "xthmqe_itru_fullheal", 						friendly_name = "Лечение ряжелых ранений"	 	},
	{ item_instance = "xthmqe_itru_pallightheal", 						friendly_name = "Малое исцеление"	 	},
	{ item_instance = "xthmqe_itru_palmediumheal", 						friendly_name = "Среднее исцеление"	 	},
	{ item_instance = "xthmqe_itru_palfullheal", 						friendly_name = "Большое исцеление"	 	},
	{ item_instance = "xthmqe_itru_harmundead", 						friendly_name = "Уничтожение нежити"	 	},
	{ item_instance = "xthmqe_itru_paldestroyevil", 						friendly_name = "Уничтожение зла"	 	},
	{ item_instance = "xthmqe_itru_palholybolt", 						friendly_name = "Святая стрела"	 	},
	{ item_instance = "xthmqe_itru_pallight", 						friendly_name = "Святой свет"	 	},
	{ item_instance = "xthmqe_itru_palrepelevil", 						friendly_name = "Изгнание зла"	 	},
	{ item_instance = "xthmqe_itru_masterofdisaster", 						friendly_name = "Святой удар"	 	},
	{ item_instance = "xthmqe_itru_shrink", 						friendly_name = "Уменьшение монстра"	 	},
	{ item_instance = "xthmqe_itru_sleep", 						friendly_name = "Сон"	 	},
	{ item_instance = "xthmqe_itru_sumdemon", 						friendly_name = "Вызов демона"	 	},
	{ item_instance = "xthmqe_itru_sumgobskel", 						friendly_name = "Вызов скелета гоблина"	 	},
	{ item_instance = "xthmqe_itru_sumgol", 						friendly_name = "Вызов голема"	 	},
	{ item_instance = "xthmqe_itru_summonguardian", 						friendly_name = "Вызов Стража"	 	},
	{ item_instance = "xthmqe_itru_summonzombie", 						friendly_name = "Вызов зомби"	 	},
	{ item_instance = "xthmqe_itru_sumskel", 						friendly_name = "Вызов скелета"	 	},
	{ item_instance = "xthmqe_itru_sumwolf", 						friendly_name = "Вызов волка"	 	},
	{ item_instance = "aixopt_itmi_feather", 						friendly_name = "Перо"	 	},
	{ item_instance = "aixopt_itmi_hammer", 						friendly_name = "Молот бронника"	 	}, 
	{ item_instance = "aixopt_itmi_scythe", 						friendly_name = "Коса"	 	}, 
	{ item_instance = "itrw_bolt", 						friendly_name = "Болт"	 	},
	{ item_instance = "itrw_arrow", 						friendly_name = "Стрела"	 	},  
	{ item_instance = "hfdpun_itpl_weed", 						friendly_name = "Сорняк"	 	},
	{ item_instance = "hfdpun_itpl_beet", 						friendly_name = "Свекла"	 	},
	{ item_instance = "hfdpun_itpl_swampherb", 						friendly_name = "Болотник"	 	},
	{ item_instance = "hfdpun_itpl_mana_herb_01", 						friendly_name = "Огненная крапива"	 	},
	{ item_instance = "hfdpun_itpl_mana_herb_02", 						friendly_name = "Огненная трава"	 	},
	{ item_instance = "hfdpun_itpl_mana_herb_03", 						friendly_name = "Огненный корень"	 	},
	{ item_instance = "hfdpun_itpl_health_herb_01", 						friendly_name = "Лечебное растение"	 	},
	{ item_instance = "hfdpun_itpl_health_herb_02", 						friendly_name = "Лечебная трава"	 	},
	{ item_instance = "hfdpun_itpl_health_herb_03", 						friendly_name = "Лечебный корень"	 	},
	{ item_instance = "hfdpun_itpl_dex_herb_01", 						friendly_name = "Ягода гоблина"	 	},
	{ item_instance = "hfdpun_itpl_strength_herb_01", 						friendly_name = "Драконий корень"	 	},
	{ item_instance = "hfdpun_itpl_speed_herb_01", 						friendly_name = "Снеппер-трава"	 	},
	{ item_instance = "hfdpun_itpl_mushroom_01", 						friendly_name = "Темный гриб"	 	},
	{ item_instance = "hfdpun_itpl_mushroom_02", 						friendly_name = "Мясной гриб"	 	},
	{ item_instance = "hfdpun_itpl_blueplant", 						friendly_name = "Серафис"	 	},
	{ item_instance = "hfdpun_itpl_forestberry", 						friendly_name = "Лесная ягода"	 	},
	{ item_instance = "hfdpun_itpl_rivermirt", 						friendly_name = "Речной мирт"	 	},
	{ item_instance = "hfdpun_itpl_siltmirt", 						friendly_name = "Иловый мирт"	 	},
	{ item_instance = "hfdpun_itpl_planeberry", 						friendly_name = "Дикая ягода"	 	},
	{ item_instance = "hfdpun_itpl_temp_herb", 						friendly_name = "Полевое растение"	 	},
	{ item_instance = "hfdpun_itpl_perm_herb", 						friendly_name = "Коронное растение"	 	},
	{ item_instance = "hfdpun_itfo_plants_berrys_01", 				friendly_name = "Кровавая ягода"	 	},
	{ item_instance = "hfdpun_itfo_plants_flameberry_01", 			friendly_name = "Огненная ягода"	 	},
	{ item_instance = "hfdpun_itfo_plants_velayis_01", 				friendly_name = "Велейс"	 	},
	{ item_instance = "hfdpun_itfo_plants_mountainmoss_01", 		friendly_name = "Горный мох"	 	},
	{ item_instance = "hfdpun_itfo_plants_mountainmoss_02", 		friendly_name = "Могильный мох"	 	},
	{ item_instance = "hfdpun_itfo_plants_nightshadow_01", 			friendly_name = "Солнечник"	 	},
	{ item_instance = "hfdpun_itfo_plants_nightshadow_02", 			friendly_name = "Лунник"	 	},
	{ item_instance = "hfdpun_itfo_plants_orcherb_01", 				friendly_name = "Орочий лист"	 	},
	{ item_instance = "hfdpun_itfo_plants_orcherb_02", 				friendly_name = "Дубовый лист"	 	},
	{ item_instance = "hfdpun_itfo_plants_bloodwood_01", 			friendly_name = "Семена бука"	 	},
	{ item_instance = "hfdpun_itfo_plants_towerwood_01", 			friendly_name = "Желуди"	 	},
	{ item_instance = "hfdpun_itfo_plants_ravenherb_01", 			friendly_name = "Воронья трава"	 	},
	{ item_instance = "hfdpun_itfo_plants_ravenherb_02", 			friendly_name = "Темные травы"	 	},
	{ item_instance = "hfdpun_itfo_plants_stoneroot_01", 			friendly_name = "Каменный корень"	 	},
	{ item_instance = "hfdpun_itfo_plants_stoneroot_02", 			friendly_name = "Драконья трава"	 	},
	{ item_instance = "hfdpun_itfo_plants_trollberrys_01", 			friendly_name = "Вишня троллей"	 	},
	{ item_instance = "hfdpun_itpl_muhomor", 						friendly_name = "Гриб провидения"	 	},
	{ item_instance = "qbduuo_itke_lockpick", 						friendly_name = "Отмычка"	 	},
	{ item_instance = "qbduuo_itke_key_cityhall", 						friendly_name = "Ключ от ратуши"	 	},
	{ item_instance = "qbduuo_itke_key_citygate", 						friendly_name = "Ключ от городских ворот"	 	},
	{ item_instance = "qbduuo_itke_key_bank", 						friendly_name = "Ключ от банка"	 	},
	{ item_instance = "qbduuo_itke_key_court", 						friendly_name = "Ключ от суда"	 	},
	{ item_instance = "qbduuo_itke_key_prison_door", 						friendly_name = "Ключ от тюрьмы"	 	},
	{ item_instance = "itke_thiefguildkey_mis", 					friendly_name = "Ключ от канализации"	 	},
	{ item_instance = "qbduuo_itke_key_prison_1", 						friendly_name = "Ключ от камеры 1"	 	},
	{ item_instance = "qbduuo_itke_key_prison_2", 						friendly_name = "Ключ от камеры 2"	 	},
	{ item_instance = "qbduuo_itke_key_prison_3", 						friendly_name = "Ключ от камеры 3"	 	},
	{ item_instance = "qbduuo_itke_key_barracks", 						friendly_name = "Ключ от казармы"	 	},
	{ item_instance = "qbduuo_itke_key_tavern_01", 						friendly_name = "Ключ от таверны 1"	 	},
	{ item_instance = "qbduuo_itke_key_tavern_02", 						friendly_name = "Ключ от таверны 2"	 	},
	{ item_instance = "qbduuo_itke_key_tavern_03", 						friendly_name = "Ключ от таверны 3"	 	},
	{ item_instance = "qbduuo_itke_key_brothel", 						friendly_name = "Ключ от борделя"	 	},
	{ item_instance = "qbduuo_itke_key_warehouse_01", 					friendly_name = "Ключ от склада 1"	 	},
	{ item_instance = "qbduuo_itke_key_warehouse_02", 					friendly_name = "Ключ от склада 2"	 	},
	{ item_instance = "qbduuo_itke_key_hotel", 							friendly_name = "Ключ от гостиницы"	 	},
	{ item_instance = "qbduuo_itke_key_monastery", 						friendly_name = "Ключ от монастыря"	 	},
	{ item_instance = "itke_klosterbibliothek", 						friendly_name = "Ключ от библиотеки"	 	},
	{ item_instance = "qbduuo_itke_key_lighthouse", 					friendly_name = "Ключ от маяка"	 	},
	{ item_instance = "qbduuo_itke_key_mines", 							friendly_name = "Ключ от шахт"	 	},
	{ item_instance = "qbduuo_itke_key_tower_1", 						friendly_name = "Ключ от башни 1"	 	},
	{ item_instance = "qbduuo_itke_key_tower_2", 						friendly_name = "Ключ от башни 2"	 	},
	{ item_instance = "qbduuo_itke_key_tower_3", 						friendly_name = "Ключ от башни 3"	 	},
	{ item_instance = "qbduuo_itke_key_tower_4", 						friendly_name = "Ключ от башни 4"	 	},
	{ item_instance = "qbduuo_itke_key_tower_5", 						friendly_name = "Ключ от башни 5"	 	},
	{ item_instance = "qbduuo_itke_key_tower_6", 						friendly_name = "Ключ от башни 6"	 	},
	{ item_instance = "qbduuo_itke_key_1", 						friendly_name = "Ключ от дома 1"	 	},
	{ item_instance = "qbduuo_itke_key_2", 						friendly_name = "Ключ от дома 2"	 	},
	{ item_instance = "qbduuo_itke_key_3", 						friendly_name = "Ключ от дома 3"	 	},
	{ item_instance = "qbduuo_itke_key_4", 						friendly_name = "Ключ от дома 4"	 	},
	{ item_instance = "qbduuo_itke_key_5", 						friendly_name = "Ключ от дома 5"	 	},
	{ item_instance = "qbduuo_itke_key_6", 						friendly_name = "Ключ от дома 6"	 	},
	{ item_instance = "qbduuo_itke_key_7", 						friendly_name = "Ключ от дома 7"	 	},
	{ item_instance = "qbduuo_itke_key_8", 						friendly_name = "Ключ от дома 8"	 	},
	{ item_instance = "qbduuo_itke_key_9", 						friendly_name = "Ключ от дома 9"	 	},
	{ item_instance = "qbduuo_itke_key_10", 						friendly_name = "Ключ от дома 10"	 	},
	{ item_instance = "qbduuo_itke_key_11", 						friendly_name = "Ключ от дома 11"	 	},
	{ item_instance = "qbduuo_itke_key_12", 						friendly_name = "Ключ от дома 12"	 	},
	{ item_instance = "qbduuo_itke_key_13", 						friendly_name = "Ключ от дома 13"	 	},
	{ item_instance = "qbduuo_itke_key_14", 						friendly_name = "Ключ от дома 14"	 	},
	{ item_instance = "qbduuo_itke_key_15", 						friendly_name = "Ключ от дома 15"	 	},
	{ item_instance = "qbduuo_itke_key_16", 						friendly_name = "Ключ от дома 16"	 	},
	{ item_instance = "qbduuo_itke_key_17", 						friendly_name = "Ключ от дома 17"	 	},
	{ item_instance = "qbduuo_itke_key_18", 						friendly_name = "Ключ от дома 18"	 	},
	{ item_instance = "qbduuo_itke_key_19", 						friendly_name = "Ключ от дома 19"	 	},
	{ item_instance = "qbduuo_itke_key_20", 						friendly_name = "Ключ от дома 20"	 	},
	{ item_instance = "qbduuo_itke_key_21", 						friendly_name = "Ключ от дома 21"	 	},
	{ item_instance = "qbduuo_itke_key_22", 						friendly_name = "Ключ от дома 22"	 	},
	{ item_instance = "qbduuo_itke_key_23", 						friendly_name = "Ключ от дома 23"	 	},
	{ item_instance = "qbduuo_itke_key_24", 						friendly_name = "Ключ от дома 24"	 	},
	{ item_instance = "qbduuo_itke_key_25", 						friendly_name = "Ключ от дома 25"	 	},
	{ item_instance = "qbduuo_itke_key_26", 						friendly_name = "Ключ от дома 26"	 	},
	{ item_instance = "qbduuo_itke_key_27", 						friendly_name = "Ключ от дома 27"	 	},
	{ item_instance = "qbduuo_itke_key_28", 						friendly_name = "Ключ от дома 28"	 	},
	{ item_instance = "qbduuo_itke_key_29", 						friendly_name = "Ключ от дома 29"	 	},
	{ item_instance = "qbduuo_itke_key_30", 						friendly_name = "Ключ от дома 30"	 	},
	{ item_instance = "qbduuo_itke_key_31", 						friendly_name = "Ключ от дома 31"	 	},
	{ item_instance = "qbduuo_itke_key_32", 						friendly_name = "Ключ от дома 32"	 	},
	{ item_instance = "qbduuo_itke_key_33", 						friendly_name = "Ключ от дома 33"	 	},
	{ item_instance = "qbduuo_itke_key_34", 						friendly_name = "Ключ от дома 34"	 	},
	{ item_instance = "qbduuo_itke_key_35", 						friendly_name = "Ключ от дома 35"	 	},
	{ item_instance = "qbduuo_itke_key_36", 						friendly_name = "Ключ от дома 36"	 	},
	{ item_instance = "qbduuo_itke_key_37", 						friendly_name = "Ключ от дома 37"	 	},
	{ item_instance = "qbduuo_itke_key_38", 						friendly_name = "Ключ от дома 38"	 	},
	{ item_instance = "qbduuo_itke_key_39", 						friendly_name = "Ключ от дома 39"	 	},
	{ item_instance = "qbduuo_itke_key_40", 						friendly_name = "Ключ от дома 40"	 	},
	{ item_instance = "qbduuo_itke_key_41", 						friendly_name = "Ключ от дома 41"	 	},
	{ item_instance = "qbduuo_itke_key_42", 						friendly_name = "Ключ от дома 42"	 	},
	{ item_instance = "qbduuo_itke_key_43", 						friendly_name = "Ключ от дома 43"	 	},
	{ item_instance = "qbduuo_itke_key_44", 						friendly_name = "Ключ от дома 44"	 	},
	{ item_instance = "qbduuo_itke_key_45", 						friendly_name = "Ключ от дома 45"	 	},
	{ item_instance = "qbduuo_itke_key_46", 						friendly_name = "Ключ от дома 46"	 	},
	{ item_instance = "qbduuo_itke_key_47", 						friendly_name = "Ключ от дома 47"	 	},
	{ item_instance = "qbduuo_itke_key_48", 						friendly_name = "Ключ от дома 48"	 	},
	{ item_instance = "qbduuo_itke_key_49", 						friendly_name = "Ключ от дома 49"	 	},
	{ item_instance = "qbduuo_itke_key_50", 						friendly_name = "Ключ от дома 50"	 	},
	{ item_instance = "qbduuo_itke_key_51", 						friendly_name = "Ключ от дома 51"	 	},
	{ item_instance = "qbduuo_itke_key_52", 						friendly_name = "Ключ от дома 52"	 	},
	{ item_instance = "qbduuo_itke_key_53", 						friendly_name = "Ключ от дома 53"	 	},
	{ item_instance = "qbduuo_itke_key_54", 						friendly_name = "Ключ от дома 54"	 	},
	{ item_instance = "qbduuo_itke_key_55", 						friendly_name = "Ключ от дома 55"	 	},
	{ item_instance = "qbduuo_itke_key_56", 						friendly_name = "Ключ от дома 56"	 	},
	{ item_instance = "qbduuo_itke_key_57", 						friendly_name = "Ключ от дома 57"	 	},
	{ item_instance = "qbduuo_itke_key_58", 						friendly_name = "Ключ от дома 58"	 	},
	{ item_instance = "qbduuo_itke_key_59", 						friendly_name = "Ключ от дома 59"	 	},
	{ item_instance = "qbduuo_itke_key_60", 						friendly_name = "Ключ от дома 60"	 	},
	{ item_instance = "qbduuo_itke_key_61", 						friendly_name = "Ключ от дома 61"	 	},
	{ item_instance = "qbduuo_itke_key_62", 						friendly_name = "Ключ от дома 62"	 	},
	{ item_instance = "qbduuo_itke_key_63", 						friendly_name = "Ключ от дома 63"	 	},
	{ item_instance = "qbduuo_itke_key_64", 						friendly_name = "Ключ от дома 64"	 	},
	{ item_instance = "qbduuo_itke_key_65", 						friendly_name = "Ключ от дома 65"	 	},
	{ item_instance = "qbduuo_itke_key_66", 						friendly_name = "Ключ от дома 66"	 	},
	{ item_instance = "qbduuo_itke_key_67", 						friendly_name = "Ключ от дома 67"	 	},
	{ item_instance = "qbduuo_itke_key_68", 						friendly_name = "Ключ от дома 68"	 	},
	{ item_instance = "qbduuo_itke_key_69", 						friendly_name = "Ключ от дома 69"	 	},
	{ item_instance = "qbduuo_itke_key_70", 						friendly_name = "Ключ от дома 70"	 	},
	{ item_instance = "qbduuo_itke_key_71", 						friendly_name = "Ключ от дома 71"	 	},
	{ item_instance = "qbduuo_itke_key_72", 						friendly_name = "Ключ от дома 72"	 	},
	{ item_instance = "qbduuo_itke_key_73", 						friendly_name = "Ключ от дома 73"	 	},
	{ item_instance = "qbduuo_itke_key_74", 						friendly_name = "Ключ от дома 74"	 	},
	{ item_instance = "qbduuo_itke_key_75", 						friendly_name = "Ключ от дома 75"	 	},
	{ item_instance = "qbduuo_itke_key_76", 						friendly_name = "Ключ от дома 76"	 	},
	{ item_instance = "qbduuo_itke_key_77", 						friendly_name = "Ключ от дома 77"	 	},
	{ item_instance = "qbduuo_itke_key_78", 						friendly_name = "Ключ от дома 78"	 	},
	{ item_instance = "qbduuo_itke_key_79", 						friendly_name = "Ключ от дома 79"	 	},
	{ item_instance = "qbduuo_itke_key_80", 						friendly_name = "Ключ от дома 80"	 	},
	{ item_instance = "qbduuo_itke_key_81", 						friendly_name = "Ключ от дома 81"	 	},
	{ item_instance = "qbduuo_itke_key_82", 						friendly_name = "Ключ от дома 82"	 	},
	{ item_instance = "qbduuo_itke_key_83", 						friendly_name = "Ключ от дома 83"	 	},
	{ item_instance = "qbduuo_itke_key_84", 						friendly_name = "Ключ от дома 84"	 	},
	{ item_instance = "qbduuo_itke_key_85", 						friendly_name = "Ключ от дома 85"	 	},
	{ item_instance = "qbduuo_itke_key_86", 						friendly_name = "Ключ от дома 86"	 	},
	{ item_instance = "qbduuo_itke_key_87", 						friendly_name = "Ключ от дома 87"	 	},
	{ item_instance = "qbduuo_itke_key_88", 						friendly_name = "Ключ от дома 88"	 	},
	{ item_instance = "qbduuo_itke_key_89", 						friendly_name = "Ключ от дома 89"	 	},
	{ item_instance = "qbduuo_itke_key_90", 						friendly_name = "Ключ от дома 90"	 	},
	{ item_instance = "qbduuo_itke_key_91", 						friendly_name = "Ключ от дома 91"	 	},
	{ item_instance = "qbduuo_itke_key_92", 						friendly_name = "Ключ от дома 92"	 	},
	{ item_instance = "qbduuo_itke_key_93", 						friendly_name = "Ключ от дома 93"	 	},
	{ item_instance = "qbduuo_itke_key_94", 						friendly_name = "Ключ от дома 94"	 	},
	{ item_instance = "qbduuo_itke_key_95", 						friendly_name = "Ключ от дома 95"	 	},
	{ item_instance = "qbduuo_itke_key_96", 						friendly_name = "Ключ от дома 96"	 	},
	{ item_instance = "qbduuo_itke_key_97", 						friendly_name = "Ключ от дома 97"	 	},
	{ item_instance = "qbduuo_itke_key_98", 						friendly_name = "Ключ от дома 98"	 	},
	{ item_instance = "qbduuo_itke_key_99", 						friendly_name = "Ключ от дома 99"	 	},
	{ item_instance = "qbduuo_itke_key_100", 						friendly_name = "Ключ от дома 100"	 	},
	{ item_instance = "qbduuo_itke_key_101", 						friendly_name = "Ключ от дома 101"	 	},
	{ item_instance = "qbduuo_itke_key_102", 						friendly_name = "Ключ от дома 102"	 	},
	{ item_instance = "qbduuo_itke_key_103", 						friendly_name = "Ключ от дома 103"	 	},
	{ item_instance = "qbduuo_itke_key_104", 						friendly_name = "Ключ от дома 104"	 	},
	{ item_instance = "qbduuo_itke_key_105", 						friendly_name = "Ключ от дома 105"	 	},
	{ item_instance = "qbduuo_itke_key_106", 						friendly_name = "Ключ от дома 106"	 	},
	{ item_instance = "qbduuo_itke_key_107", 						friendly_name = "Ключ от дома 107"	 	},
	{ item_instance = "qbduuo_itke_key_108", 						friendly_name = "Ключ от дома 108"	 	},
	{ item_instance = "qbduuo_itke_key_109", 						friendly_name = "Ключ от дома 109"	 	},
	{ item_instance = "qbduuo_itke_key_110", 						friendly_name = "Ключ от дома 110"	 	},
	{ item_instance = "qbduuo_itke_key_111", 						friendly_name = "Ключ от дома 111"	 	},
	{ item_instance = "qbduuo_itke_key_112", 						friendly_name = "Ключ от дома 112"	 	},
	{ item_instance = "qbduuo_itke_key_113", 						friendly_name = "Ключ от дома 113"	 	},
	{ item_instance = "qbduuo_itke_key_114", 						friendly_name = "Ключ от дома 114"	 	},
	{ item_instance = "qbduuo_itke_key_115", 						friendly_name = "Ключ от дома 115"	 	},
	{ item_instance = "qbduuo_itke_key_116", 						friendly_name = "Ключ от дома 116"	 	},
	{ item_instance = "qbduuo_itke_key_117", 						friendly_name = "Ключ от дома 117"	 	},
	{ item_instance = "qbduuo_itke_key_118", 						friendly_name = "Ключ от дома 118"	 	},
	{ item_instance = "qbduuo_itke_key_119", 						friendly_name = "Ключ от дома 119"	 	},
	{ item_instance = "qbduuo_itke_key_120", 						friendly_name = "Ключ от дома 120"	 	},
	{ item_instance = "qbduuo_itke_key_121", 						friendly_name = "Ключ от дома 121"	 	},
	{ item_instance = "qbduuo_itke_key_122", 						friendly_name = "Ключ от дома 122"	 	},
	{ item_instance = "qbduuo_itke_key_123", 						friendly_name = "Ключ от дома 123"	 	},
	{ item_instance = "qbduuo_itke_key_124", 						friendly_name = "Ключ от дома 124"	 	},
	{ item_instance = "qbduuo_itke_key_125", 						friendly_name = "Ключ от дома 125"	 	},
	{ item_instance = "qbduuo_itke_key_126", 						friendly_name = "Ключ от дома 126"	 	},
	{ item_instance = "qbduuo_itke_key_127", 						friendly_name = "Ключ от дома 127"	 	},
	{ item_instance = "qbduuo_itke_key_128", 						friendly_name = "Ключ от дома 128"	 	},
	{ item_instance = "qbduuo_itke_key_129", 						friendly_name = "Ключ от дома 129"	 	},
	{ item_instance = "qbduuo_itke_key_130", 						friendly_name = "Ключ от дома 130"	 	},
	{ item_instance = "qbduuo_itke_key_131", 						friendly_name = "Ключ от дома 131"	 	},
	{ item_instance = "qbduuo_itke_key_132", 						friendly_name = "Ключ от дома 132"	 	},
	{ item_instance = "qbduuo_itke_key_133", 						friendly_name = "Ключ от дома 133"	 	},
	{ item_instance = "qbduuo_itke_key_134", 						friendly_name = "Ключ от дома 134"	 	},
	{ item_instance = "qbduuo_itke_key_135", 						friendly_name = "Ключ от дома 135"	 	},
	{ item_instance = "qbduuo_itke_key_136", 						friendly_name = "Ключ от дома 136"	 	},
	{ item_instance = "qbduuo_itke_key_137", 						friendly_name = "Ключ от дома 137"	 	},
	{ item_instance = "qbduuo_itke_key_138", 						friendly_name = "Ключ от дома 138"	 	},
	{ item_instance = "qbduuo_itke_key_139", 						friendly_name = "Ключ от дома 139"	 	},
	{ item_instance = "qbduuo_itke_key_140", 						friendly_name = "Ключ от дома 140"	 	},
	{ item_instance = "qbduuo_itke_key_141", 						friendly_name = "Ключ от дома 141"	 	},
	{ item_instance = "qbduuo_itke_key_142", 						friendly_name = "Ключ от дома 142"	 	},
	{ item_instance = "qbduuo_itke_key_143", 						friendly_name = "Ключ от дома 143"	 	},
	{ item_instance = "qbduuo_itke_key_144", 						friendly_name = "Ключ от дома 144"	 	},
	{ item_instance = "qbduuo_itke_key_145", 						friendly_name = "Ключ от дома 145"	 	},
	{ item_instance = "qbduuo_itke_key_146", 						friendly_name = "Ключ от дома 146"	 	},
	{ item_instance = "qbduuo_itke_key_147", 						friendly_name = "Ключ от дома 147"	 	},
	{ item_instance = "qbduuo_itke_key_148", 						friendly_name = "Ключ от дома 148"	 	},
	{ item_instance = "qbduuo_itke_key_149", 						friendly_name = "Ключ от дома 149"	 	},
	{ item_instance = "qbduuo_itke_key_150", 						friendly_name = "Ключ от дома 150"	 	},
	{ item_instance = "qbduuo_itke_keychest_1", 						friendly_name = "Ключ от сундука 1"	 	},
	{ item_instance = "qbduuo_itke_keychest_2", 						friendly_name = "Ключ от сундука 2"	 	},
	{ item_instance = "qbduuo_itke_keychest_3", 						friendly_name = "Ключ от сундука 3"	 	},
	{ item_instance = "qbduuo_itke_keychest_4", 						friendly_name = "Ключ от сундука 4"	 	},
	{ item_instance = "qbduuo_itke_keychest_5", 						friendly_name = "Ключ от сундука 5"	 	},
	{ item_instance = "qbduuo_itke_keychest_6", 						friendly_name = "Ключ от сундука 6"	 	},
	{ item_instance = "qbduuo_itke_keychest_7", 						friendly_name = "Ключ от сундука 7"	 	},
	{ item_instance = "qbduuo_itke_keychest_8", 						friendly_name = "Ключ от сундука 8"	 	},
	{ item_instance = "qbduuo_itke_keychest_9", 						friendly_name = "Ключ от сундука 9"	 	},
	{ item_instance = "qbduuo_itke_keychest_10", 						friendly_name = "Ключ от сундука 10"	 	},
	{ item_instance = "qbduuo_itke_keychest_11", 						friendly_name = "Ключ от сундука 11"	 	},
	{ item_instance = "qbduuo_itke_keychest_12", 						friendly_name = "Ключ от сундука 12"	 	},
	{ item_instance = "qbduuo_itke_keychest_13", 						friendly_name = "Ключ от сундука 13"	 	},
	{ item_instance = "qbduuo_itke_keychest_14", 						friendly_name = "Ключ от сундука 14"	 	},
	{ item_instance = "qbduuo_itke_keychest_15", 						friendly_name = "Ключ от сундука 15"	 	},
	{ item_instance = "qbduuo_itke_keychest_16", 						friendly_name = "Ключ от сундука 16"	 	},
	{ item_instance = "qbduuo_itke_keychest_17", 						friendly_name = "Ключ от сундука 17"	 	},
	{ item_instance = "qbduuo_itke_keychest_18", 						friendly_name = "Ключ от сундука 18"	 	},
	{ item_instance = "qbduuo_itke_keychest_19", 						friendly_name = "Ключ от сундука 19"	 	},
	{ item_instance = "qbduuo_itke_keychest_20", 						friendly_name = "Ключ от сундука 20"	 	},
	{ item_instance = "qbduuo_itke_keychest_21", 						friendly_name = "Ключ от сундука 21"	 	},
	{ item_instance = "qbduuo_itke_keychest_22", 						friendly_name = "Ключ от сундука 22"	 	},
	{ item_instance = "qbduuo_itke_keychest_23", 						friendly_name = "Ключ от сундука 23"	 	},
	{ item_instance = "qbduuo_itke_keychest_24", 						friendly_name = "Ключ от сундука 24"	 	},
	{ item_instance = "qbduuo_itke_keychest_25", 						friendly_name = "Ключ от сундука 25"	 	},
	{ item_instance = "qbduuo_itke_keychest_26", 						friendly_name = "Ключ от сундука 26"	 	},
	{ item_instance = "qbduuo_itke_keychest_27", 						friendly_name = "Ключ от сундука 27"	 	},
	{ item_instance = "qbduuo_itke_keychest_28", 						friendly_name = "Ключ от сундука 28"	 	},
	{ item_instance = "qbduuo_itke_keychest_29", 						friendly_name = "Ключ от сундука 29"	 	},
	{ item_instance = "qbduuo_itke_keychest_30", 						friendly_name = "Ключ от сундука 30"	 	},
	{ item_instance = "qbduuo_itke_keychest_31", 						friendly_name = "Ключ от сундука 31"	 	},
	{ item_instance = "qbduuo_itke_keychest_32", 						friendly_name = "Ключ от сундука 32"	 	},
	{ item_instance = "qbduuo_itke_keychest_33", 						friendly_name = "Ключ от сундука 33"	 	},
	{ item_instance = "qbduuo_itke_keychest_34", 						friendly_name = "Ключ от сундука 34"	 	},
	{ item_instance = "qbduuo_itke_keychest_35", 						friendly_name = "Ключ от сундука 35"	 	},
	{ item_instance = "qbduuo_itke_keychest_36", 						friendly_name = "Ключ от сундука 36"	 	},
	{ item_instance = "qbduuo_itke_keychest_37", 						friendly_name = "Ключ от сундука 37"	 	},
	{ item_instance = "qbduuo_itke_keychest_38", 						friendly_name = "Ключ от сундука 38"	 	},
	{ item_instance = "qbduuo_itke_keychest_39", 						friendly_name = "Ключ от сундука 39"	 	},
	{ item_instance = "qbduuo_itke_keychest_40", 						friendly_name = "Ключ от сундука 40"	 	},
	{ item_instance = "qbduuo_itke_keychest_41", 						friendly_name = "Ключ от сундука 41"	 	},
	{ item_instance = "qbduuo_itke_keychest_42", 						friendly_name = "Ключ от сундука 42"	 	},
	{ item_instance = "qbduuo_itke_keychest_43", 						friendly_name = "Ключ от сундука 43"	 	},
	{ item_instance = "qbduuo_itke_keychest_44", 						friendly_name = "Ключ от сундука 44"	 	},
	{ item_instance = "qbduuo_itke_keychest_45", 						friendly_name = "Ключ от сундука 45"	 	},
	{ item_instance = "qbduuo_itke_keychest_46", 						friendly_name = "Ключ от сундука 46"	 	},
	{ item_instance = "qbduuo_itke_keychest_47", 						friendly_name = "Ключ от сундука 47"	 	},
	{ item_instance = "qbduuo_itke_keychest_48", 						friendly_name = "Ключ от сундука 48"	 	},
	{ item_instance = "qbduuo_itke_keychest_49", 						friendly_name = "Ключ от сундука 49"	 	},
	{ item_instance = "qbduuo_itke_keychest_50", 						friendly_name = "Ключ от сундука 50"	 	},
	{ item_instance = "qbduuo_itke_keychest_51", 						friendly_name = "Ключ от сундука 51"	 	},
	{ item_instance = "qbduuo_itke_keychest_52", 						friendly_name = "Ключ от сундука 52"	 	},
	{ item_instance = "qbduuo_itke_keychest_53", 						friendly_name = "Ключ от сундука 53"	 	},
	{ item_instance = "qbduuo_itke_keychest_54", 						friendly_name = "Ключ от сундука 54"	 	},
	{ item_instance = "qbduuo_itke_keychest_55", 						friendly_name = "Ключ от сундука 55"	 	},
	{ item_instance = "qbduuo_itke_keychest_56", 						friendly_name = "Ключ от сундука 56"	 	},
	{ item_instance = "qbduuo_itke_keychest_57", 						friendly_name = "Ключ от сундука 57"	 	},
	{ item_instance = "qbduuo_itke_keychest_58", 						friendly_name = "Ключ от сундука 58"	 	},
	{ item_instance = "qbduuo_itke_keychest_59", 						friendly_name = "Ключ от сундука 59"	 	},
	{ item_instance = "qbduuo_itke_keychest_60", 						friendly_name = "Ключ от сундука 60"	 	},
	{ item_instance = "qbduuo_itke_keychest_61", 						friendly_name = "Ключ от сундука 61"	 	},
	{ item_instance = "qbduuo_itke_keychest_62", 						friendly_name = "Ключ от сундука 62"	 	},
	{ item_instance = "qbduuo_itke_keychest_63", 						friendly_name = "Ключ от сундука 63"	 	},
	{ item_instance = "qbduuo_itke_keychest_64", 						friendly_name = "Ключ от сундука 64"	 	},
	{ item_instance = "qbduuo_itke_keychest_65", 						friendly_name = "Ключ от сундука 65"	 	},
	{ item_instance = "qbduuo_itke_keychest_66", 						friendly_name = "Ключ от сундука 66"	 	},
	{ item_instance = "qbduuo_itke_keychest_67", 						friendly_name = "Ключ от сундука 67"	 	},
	{ item_instance = "qbduuo_itke_keychest_68", 						friendly_name = "Ключ от сундука 68"	 	},
	{ item_instance = "qbduuo_itke_keychest_69", 						friendly_name = "Ключ от сундука 69"	 	},
	{ item_instance = "qbduuo_itke_keychest_70", 						friendly_name = "Ключ от сундука 70"	 	},
	{ item_instance = "qbduuo_itke_keychest_71", 						friendly_name = "Ключ от сундука 71"	 	},
	{ item_instance = "qbduuo_itke_keychest_72", 						friendly_name = "Ключ от сундука 72"	 	},
	{ item_instance = "qbduuo_itke_keychest_73", 						friendly_name = "Ключ от сундука 73"	 	},
	{ item_instance = "qbduuo_itke_keychest_74", 						friendly_name = "Ключ от сундука 74"	 	},
	{ item_instance = "qbduuo_itke_keychest_75", 						friendly_name = "Ключ от сундука 75"	 	},
	{ item_instance = "qbduuo_itke_keychest_76", 						friendly_name = "Ключ от сундука 76"	 	},
	{ item_instance = "qbduuo_itke_keychest_77", 						friendly_name = "Ключ от сундука 77"	 	},
	{ item_instance = "qbduuo_itke_keychest_78", 						friendly_name = "Ключ от сундука 78"	 	},
	{ item_instance = "qbduuo_itke_keychest_79", 						friendly_name = "Ключ от сундука 79"	 	},
	{ item_instance = "qbduuo_itke_keychest_80", 						friendly_name = "Ключ от сундука 80"	 	},
	{ item_instance = "qbduuo_itke_keychest_81", 						friendly_name = "Ключ от сундука 81"	 	},
	{ item_instance = "qbduuo_itke_keychest_82", 						friendly_name = "Ключ от сундука 82"	 	},
	{ item_instance = "qbduuo_itke_keychest_83", 						friendly_name = "Ключ от сундука 83"	 	},
	{ item_instance = "qbduuo_itke_keychest_84", 						friendly_name = "Ключ от сундука 84"	 	},
	{ item_instance = "qbduuo_itke_keychest_85", 						friendly_name = "Ключ от сундука 85"	 	},
	{ item_instance = "qbduuo_itke_keychest_86", 						friendly_name = "Ключ от сундука 86"	 	},
	{ item_instance = "qbduuo_itke_keychest_87", 						friendly_name = "Ключ от сундука 87"	 	},
	{ item_instance = "qbduuo_itke_keychest_88", 						friendly_name = "Ключ от сундука 88"	 	},
	{ item_instance = "qbduuo_itke_keychest_89", 						friendly_name = "Ключ от сундука 89"	 	},
	{ item_instance = "qbduuo_itke_keychest_90", 						friendly_name = "Ключ от сундука 90"	 	},
	{ item_instance = "qbduuo_itke_keychest_91", 						friendly_name = "Ключ от сундука 91"	 	},
	{ item_instance = "qbduuo_itke_keychest_92", 						friendly_name = "Ключ от сундука 92"	 	},
	{ item_instance = "qbduuo_itke_keychest_93", 						friendly_name = "Ключ от сундука 93"	 	},
	{ item_instance = "qbduuo_itke_keychest_94", 						friendly_name = "Ключ от сундука 94"	 	},
	{ item_instance = "qbduuo_itke_keychest_95", 						friendly_name = "Ключ от сундука 95"	 	},
	{ item_instance = "qbduuo_itke_keychest_96", 						friendly_name = "Ключ от сундука 96"	 	},
	{ item_instance = "qbduuo_itke_keychest_97", 						friendly_name = "Ключ от сундука 97"	 	},
	{ item_instance = "qbduuo_itke_keychest_98", 						friendly_name = "Ключ от сундука 98"	 	},
	{ item_instance = "qbduuo_itke_keychest_99", 						friendly_name = "Ключ от сундука 99"	 	},
	{ item_instance = "qbduuo_itke_keychest_100", 						friendly_name = "Ключ от сундука 100"	 	},
	{ item_instance = "qbduuo_itke_keychest_101", 						friendly_name = "Ключ от сундука 101"	 	},
	{ item_instance = "qbduuo_itke_keychest_102", 						friendly_name = "Ключ от сундука 102"	 	},
	{ item_instance = "qbduuo_itke_keychest_103", 						friendly_name = "Ключ от сундука 103"	 	},
	{ item_instance = "qbduuo_itke_keychest_104", 						friendly_name = "Ключ от сундука 104"	 	},
	{ item_instance = "qbduuo_itke_keychest_105", 						friendly_name = "Ключ от сундука 105"	 	},
	{ item_instance = "qbduuo_itke_keychest_106", 						friendly_name = "Ключ от сундука 106"	 	},
	{ item_instance = "qbduuo_itke_keychest_107", 						friendly_name = "Ключ от сундука 107"	 	},
	{ item_instance = "qbduuo_itke_keychest_108", 						friendly_name = "Ключ от сундука 108"	 	},
	{ item_instance = "qbduuo_itke_keychest_109", 						friendly_name = "Ключ от сундука 109"	 	},
	{ item_instance = "qbduuo_itke_keychest_110", 						friendly_name = "Ключ от сундука 110"	 	},
	{ item_instance = "qbduuo_itke_keychest_111", 						friendly_name = "Ключ от сундука 111"	 	},
	{ item_instance = "qbduuo_itke_keychest_112", 						friendly_name = "Ключ от сундука 112"	 	},
	{ item_instance = "qbduuo_itke_keychest_113", 						friendly_name = "Ключ от сундука 113"	 	},
	{ item_instance = "qbduuo_itke_keychest_114", 						friendly_name = "Ключ от сундука 114"	 	},
	{ item_instance = "qbduuo_itke_keychest_115", 						friendly_name = "Ключ от сундука 115"	 	},
	{ item_instance = "qbduuo_itke_keychest_116", 						friendly_name = "Ключ от сундука 116"	 	},
	{ item_instance = "qbduuo_itke_keychest_117", 						friendly_name = "Ключ от сундука 117"	 	},
	{ item_instance = "qbduuo_itke_keychest_118", 						friendly_name = "Ключ от сундука 118"	 	},
	{ item_instance = "qbduuo_itke_keychest_119", 						friendly_name = "Ключ от сундука 119"	 	},
	{ item_instance = "qbduuo_itke_keychest_120", 						friendly_name = "Ключ от сундука 120"	 	},
	{ item_instance = "qbduuo_itke_keychest_121", 						friendly_name = "Ключ от сундука 121"	 	},
	{ item_instance = "qbduuo_itke_keychest_122", 						friendly_name = "Ключ от сундука 122"	 	},
	{ item_instance = "qbduuo_itke_keychest_123", 						friendly_name = "Ключ от сундука 123"	 	},
	{ item_instance = "qbduuo_itke_keychest_124", 						friendly_name = "Ключ от сундука 124"	 	},
	{ item_instance = "qbduuo_itke_keychest_125", 						friendly_name = "Ключ от сундука 125"	 	},
	{ item_instance = "qbduuo_itke_keychest_126", 						friendly_name = "Ключ от сундука 126"	 	},
	{ item_instance = "qbduuo_itke_keychest_127", 						friendly_name = "Ключ от сундука 127"	 	},
	{ item_instance = "qbduuo_itke_keychest_128", 						friendly_name = "Ключ от сундука 128"	 	},
	{ item_instance = "qbduuo_itke_keychest_129", 						friendly_name = "Ключ от сундука 129"	 	},
	{ item_instance = "qbduuo_itke_keychest_130", 						friendly_name = "Ключ от сундука 130"	 	},
	{ item_instance = "qbduuo_itke_keychest_131", 						friendly_name = "Ключ от сундука 131"	 	},
	{ item_instance = "qbduuo_itke_keychest_132", 						friendly_name = "Ключ от сундука 132"	 	},
	{ item_instance = "qbduuo_itke_keychest_133", 						friendly_name = "Ключ от сундука 133"	 	},
	{ item_instance = "qbduuo_itke_keychest_134", 						friendly_name = "Ключ от сундука 134"	 	},
	{ item_instance = "qbduuo_itke_keychest_135", 						friendly_name = "Ключ от сундука 135"	 	},
	{ item_instance = "qbduuo_itke_keychest_136", 						friendly_name = "Ключ от сундука 136"	 	},
	{ item_instance = "qbduuo_itke_keychest_137", 						friendly_name = "Ключ от сундука 137"	 	},
	{ item_instance = "qbduuo_itke_keychest_138", 						friendly_name = "Ключ от сундука 138"	 	},
	{ item_instance = "qbduuo_itke_keychest_139", 						friendly_name = "Ключ от сундука 139"	 	},
	{ item_instance = "qbduuo_itke_keychest_140", 						friendly_name = "Ключ от сундука 140"	 	},
	{ item_instance = "qbduuo_itke_keychest_141", 						friendly_name = "Ключ от сундука 141"	 	},
	{ item_instance = "qbduuo_itke_keychest_142", 						friendly_name = "Ключ от сундука 142"	 	},
	{ item_instance = "qbduuo_itke_keychest_143", 						friendly_name = "Ключ от сундука 143"	 	},
	{ item_instance = "qbduuo_itke_keychest_144", 						friendly_name = "Ключ от сундука 144"	 	},
	{ item_instance = "qbduuo_itke_keychest_145", 						friendly_name = "Ключ от сундука 145"	 	},
	{ item_instance = "qbduuo_itke_keychest_146", 						friendly_name = "Ключ от сундука 146"	 	},
	{ item_instance = "qbduuo_itke_keychest_147", 						friendly_name = "Ключ от сундука 147"	 	},
	{ item_instance = "qbduuo_itke_keychest_148", 						friendly_name = "Ключ от сундука 148"	 	},
	{ item_instance = "qbduuo_itke_keychest_149", 						friendly_name = "Ключ от сундука 149"	 	},
	{ item_instance = "qbduuo_itke_keychest_150", 						friendly_name = "Ключ от сундука 150"	 	},
	{ item_instance = "aixopt_itmi_uniquerecipe", 						friendly_name = "Уникальный рецепт"	 	},
	{ item_instance = "aixopt_itmi_jointrecipe_01", 					friendly_name = "Рецепт болотника"	 	},
	{ item_instance = "aixopt_itmi_recipe_kdf", 						friendly_name = "Лекала роб Круга Огня"	 	},
	{ item_instance = "aixopt_itmi_recipe_kdw", 						friendly_name = "Лекала роб Круга Воды"	 	},
	{ item_instance = "aixopt_itmi_recipe_grd", 						friendly_name = "Лекала униформы стражи"	 	},
	{ item_instance = "aixopt_itmi_recipe_arx", 						friendly_name = "Лекала гильдии Араксос"	 	},
	{ item_instance = "aixopt_itmi_recipe_sld", 						friendly_name = "Чертежи доспехов наемников"	 	},
}

function GetItemName( item_instance )
	if item_instance and type( item_instance ) == "string" then
		for key, item in ipairs( inst_Items ) do
			if( string.lower( item_instance ) == item.item_instance ) then
				return item.friendly_name
			end
		end
	end
	return item_instance
end

function GetItemCode( friendly_name )
	if friendly_name and type( friendly_name ) == "string" then
		for key, item in ipairs( inst_Items ) do
			if( string.lower( friendly_name ) == item.friendly_name ) then
				return item.item_instance
			end
		end
	end
	return friendly_name
end